### ISSUE TITLE
Undesired output buffering

### ISSUE THREAD

**Issue by nmr8acme** [square/okhttp#1078]
Using URL#openConnection I am experiencing 800k of initial output buffering, followed by 100k chunks of buffering at a time. This makes it impractical to deliver a good upload progress bar experience.

![chart of output/time](https://docs.google.com/spreadsheets/d/1UwbfsgNxjlDpxS02s0ZYFfmF3_jcy5J3ZgRGyV2DuVU/pubchart?oid=936554100&format=image)

This was observed while running the connection through Charles and manually watching the transmitted bytes column of the request, observing the byte count increasing smoothly. (As opposed to ~100k bursts at ~5 second intervals)

I repeated the test without Charles proxying, and again without https, and observed the same burst behavior.

Gist with a snippet of my code, and logcat output: https://gist.github.com/nmr8acme/2a97794b428e24608960

This is running on 4.4, with

```
URL.setURLStreamHandlerFactory(new OkUrlFactory(new OkHttpClient()));
```

... applied in `Application#onCreate`. I have verified that I am getting an okhttp ~`FixedLengthSink` from `getOutputStream`.

Related to this SO question: http://stackoverflow.com/questions/23600397/okhttp-buffers-800kb-before-uploading-data-despite-flush/23608596#comment41285455_23608596

**Comment by coonmoo** [comment]
Any chance to fix this behaviour without tampering the source?

**Comment by swankjesse** [comment]
`flush()`.

**Comment by nmr8acme** [comment]
`flush()` doesn't work because the data is already in the kernel's TCP send buffer.

I used this:
```
#include "sys/ioctl.h"
#include "linux/sockios.h"

JNIEXPORT jint JNICALL Java_com_acmeaom_stuff_things_siocoutq
  (JNIEnv *env, jclass c, jobject fd) {
    if (fd == NULL) return -1;

    int pending;
    int fd_ = jniGetFDFromFileDescriptor(env, fd);
    if (fd_ < 0) {
        printf("siocoutq bad file descriptor\n");
        return fd_;
    }
    int err = ioctl(fd_, SIOCOUTQ, &pending);
    if (err != 0) {
        printf("siocoutq err %d\n", err);
        return -3;
    }
    return pending;
}
```

**Comment by slightfoot** [comment]
I found overriding the default socket factory to be a simple solution.
https://gist.github.com/slightfoot/00a26683ea68856ceb50e26c7d8a47d0

**Comment by phuongcv1112** [comment]
Love your solution Simon :)

**Comment by nmr8acme** [comment]
Yeah, his is definitely the better solution, pretty clean.

**Comment by aholic** [comment]
hello @swankjesse 

I am stuck in such a scenario:
client send a http request to server (header size: about 1000B, body size: 500B).
As I capture the packet using tcpdump in the server side(I can't make contact with my user who is the client side)
The server got the first 1360B(due to the MTU) quickly.
But after a long time(about 30s), the server got the remain 140B.
And afterwards, the server get a FIN from the client immediately.

Do you think this issue will lead to my scenario? Or any other advice?
okhttp version: 2.6.3
It will be nice if you could reply. Thank you very much.

**Comment by swankjesse** [comment]
@aholic please provide an executable test case to demonstrate the problem. Please also upgrade to the latest release before reporting further bugs.

**Comment by aholic** [comment]
@swankjesse 
Thank you for your reply 

I was searching "okhttp flush buffer" and found this issue.

It's not easy to illustrate my scenario, but I will try to make it clear for you.
We are the CDN supplier. One of our customers(companies who develop Apps) said that their App will wait for our server for a long time(30s in my scenario) in a probability(statistics in their App, about 0.1%). The wait seems fishy. We don't have client, the only thing we can do in the server side is to capture packet for long-time-last request. The packet is mentioned in my previous comment.

From the user-agent header in the packet I captured, I know they were using okhttp2.6.3. 
I guess it's a bug in the client. Their client may forget to flush whole body to our server or something like that. So I try to search "okhttp flush buffer". I want to found someone who shares the same scenario. Due to some business reason, I can't demand my customer to check their client code before I am certain of the reason.

Closing the connection led to the FIN from client. That is to say, the remain 140B data is not send until closing the connection. Is there any misusage of okhttp will lead to my scenario? 

Really tough work for me :- )

Thanks again for your reply.

**Comment by KaviPaviTwinsS** [comment]
Hi,
I faced the issue like failed to connect like Socket timout exception in Retrofit2 OkHttpClient with timout properties while network speed is low.How to handle this situation and how to get the response without timeout for that request?
