### ISSUE TITLE
Not following correct URL in redirect because of the encoding

### ISSUE THREAD

**Issue by firetrap** [square/okhttp#1534]
OkHttp is following correctly the redirect but the problem it's the URL it's encoded with a diferent charset it's not UTF-8 it's ISO-8859-1 or it can ISO-8859-15 or another one because it identify the user region on the first request.

My first call it's to the 

.../html/dynamicSpots/recuperapassdirect.jsp?user=firetrap@something.com

and the server responds with a 302 redirect, but the server know my user is Portuguese it redirects me to a URL with ISO-8859-1 with strange chars like this:

.../html/dynamicSpots/showResult.jsp?result=Pedido de recupera��o efetuado com sucesso, consulte o seu e-mail

Because it was not encoded correctly before the 2 second request (redirect)

I've disabled the redirects with setFollowRedirects(false) to handle my self the encoding but it will be good to see okhttp getting the encoding from the header and set it correctly.

**Comment by swankjesse** [comment]
Off topic: does that message show up in your user interface? Probably a lousy idea because it lends itself to injection attacks:
```
../html/dynamicSpots/showResult.jsp?result=poop
```

You should instead use URL-escaping, like so:
http://hi.wikipedia.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0
http://en.wikipedia.org/wiki/Universit%C3%A9_du_Qu%C3%A9bec_%C3%A0_Montr%C3%A9al
