### ISSUE TITLE
okio.ByteString cannot be resolved

### ISSUE THREAD

**Issue by fulingfan** [square/okhttp#1685]
okio.ByteString cannot be resolved

**Comment by JakeWharton** [comment]
Add a dependency on [Okio][1].

 [1]: https://github.com/square/okio

**Comment by fulingfan** [comment]
yes，i see it，thanks

**Comment by 9tontruck** [comment]
Hi, I am having the same problem - okio.ByteString cannot be resolved

I copied "okhttp-2.7.0.jar" to lib folder and added externer jar in the project property. I guess it's pretty much done for adding a library because I don't use gradle. 

Everything is imported nicely, and I can use the objects. But I am having the error from "RequestBody.create(JSON, json);"  What should I do to fix this error?

**Comment by JakeWharton** [comment]
Add okio-1.6.0.jar

**Comment by AdamMiltonBarker** [comment]
Also having this issue, in gradle have added the following and included the jar in libs as per the docs here:

https://square.github.io/okhttp/

Added in gradle: 

    compile 'com.squareup.okhttp3:okhttp:3.2.0'

What is missing ?
