### ISSUE TITLE
Support Link-Local IPv6 with Scope in URLs

### ISSUE THREAD

**Issue by yydl** [square/okhttp#1706]
[IPv6 link local addresses](https://en.wikipedia.org/wiki/IPv6_address#Link-local_addresses_and_zone_indices) need to specify a scope ID in order to be routed correctly. I tried making requests with URLs that contain this scope ID but OkHttp doesn't accept the url as it doesn't know how to parse it correctly.

First I tried by escaping the percent sign before the scope:

```
http://[fe80::45c:d71:aec1:9ec3%25eth0]:7001/path.file
```

This resulted in an "IllegalArgumentException: unexpected url" error

Then I tried just putting in the percent sign as is:

```
http://[fe80::45c:d71:aec1:9ec3%eth0]:7001/path.file
```

Once again, I got the same error.

**Comment by JakeWharton** [comment]
Interesting feature. Never knew this was a thing.

**Comment by swankjesse** [comment]
Explanation: https://msdn.microsoft.com/en-us/library/aa917150.aspx
Proposed Standard: https://tools.ietf.org/html/rfc6874
Chrome bug report: https://code.google.com/p/chromium/issues/detail?id=70762
Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=700999

Interesting constraint on these URLs:
> To limit this risk, implementations MUST NOT allow use of this format except for well-defined usages, such as sending to link-local addresses under prefix fe80::/10.  At the time of writing, this is the only well-defined usage known.

Next steps:
1. We'll accept a pull request to add link-local support to HttpUrl, as long as it's accompanied by appropriate tests. Preferably link local address tests are also submitted upstream to [web-platform-tests](https://github.com/w3c/web-platform-tests/tree/master/url).
2. We'll accept a pull request to honor those `HttpUrl` instances when selecting an interface for a HTTP connection. There's some nuance around link-local addresses and proxies - we connect through the proxy so that's where the scope goes.

Those interested in seeing this feature should volunteer to write those pull requests. Until then I'm putting this feature request on ice.

**Comment by marsounjan** [comment]
Hi @swankjesse, I have made a PR to support IPv6 link local addresses with interface scopes. Could you please check it out? :)

**Comment by swankjesse** [comment]
Guava implemented support by always discarding the scope ID:
https://github.com/google/guava/commit/1d3780724431da91b28bbf50fcb13f27459f4710

**Comment by yschimke** [comment]
Closing as we rejected this PR https://github.com/square/okhttp/pull/4865
