### ISSUE TITLE
OkHttp稳定性

### ISSUE THREAD

**Issue by yesanfan** [square/okhttp#1745]
想用OKHttp替换HttpClient, 网上搜索了一下OkHttp, 发现有人说OkHttp2.0有个bug, 在部分酷派手机上无法获取服务器信息，那么最新的OkHttp版本这个bug是否修复了呢？稳定不稳定呢

**Comment by swankjesse** [comment]
Can you please provide a JUnit test for the issue? I'm English-speaking only but code is the universal language.

**Comment by rpplusplus** [comment]
He said that, OKHttp doesn't work on some CoolPad devices .. 
I thought it is duplicate with https://github.com/square/okhttp/issues/1745

**Comment by yesanfan** [comment]
Hello, I want to ask , OKHttp doesn't work on some CoolPad devices ,  the latest version of OKHttp has fixed this bug? @swankjesse

**Comment by yesanfan** [comment]
Thanks! @rpplusplus

**Comment by floating-cat** [comment]
Duplicate of #1518 (forked from #1114).
This bug hasn't been fixed in OkHttp 2.4. You can find a workaround here (though I haven't test it)
https://github.com/square/okhttp/issues/1518#issuecomment-87996760

You had better [search](https://github.com/square/okhttp/search?utf8=%E2%9C%93&q=Coolpad&type=Issues) before you ask.

**Comment by swankjesse** [comment]
Fixed in the next release. https://github.com/square/okio/pull/164
