### ISSUE TITLE
Define policy on timeouts and retries

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1790]
@nfuller:

> Here: [HttpEngine.isRecoverable](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java#L440)
> The catch should be treating SocketTimeoutException (which, you'll recall, is subclass of InterruptedIOException) as a "retryable". InterruptedIOException should probably still be non-retryable In this one case. The reasoning being that timeouts can be the result of misconfigured networking, but other InterruptedIOExceptions may be a call to Thread.interrupt() (e.g. issue #1146). Other cases still look like SocketTimeoutException should be treated the same as InterruptedIOException (to me) so shouldn't need to be changed, except to point out that the logic is no longer common.

I think we should figure out what we want the policy to be, and then implement that exactly. And I think we probably want the policy to be that timeouts are short (say _5_ or _10_ seconds by default) and retries are automatic.

We need to figure out how we count various things: do 3 SSL negotiations count as a single attempt? And how many attempts to we make to a webservice with 5 IP addresses?

Until now this hasn't really been decided, and it should be! Plus we should figure out what knobs to expose.

Related: https://github.com/square/okhttp/issues/1146
And of course this: https://twitter.com/mumak/status/628489427489288192

**Comment by nfuller** [comment]
Initially I'd like to just put the behavior back the way it was (intended to be).

The Android connectivity detection code uses the HttpURLConnection and assumes (rightly or wrongly) that a certain subset of "routes" are tried (where "route" is a combination of proxy/direct, ip addresses).

Possibly related: We Android bugs raised occasionally where people have complained that HttpURLConnection.setConnectTimeout() and setReadTimeout() actually means we can wait N times those values because those timeouts are observed per socket. It's hard for apps to set a "correct" timeout in terms of "time that will actually elapse" because an arbitrary URL may resolve to an arbitrary number of socket connections (N).

However, I've mostly pushed back on any modification because it will break existing apps and any other interpretation of the URL connection timeout is also prone to problems, particularly when misconfigured networks can just blackhole connection attempts and we always run into the underlying socket timeout. For true flexibility developers would probably need separate "HTTP connect timeout" and "Socket connect timeout" settings.

**Comment by nfuller** [comment]
I have updated the commit to address most comments. I'm not sure what to do about IPv6 addresses with scopes.

**Comment by swankjesse** [comment]
I think we’re pretty good at this point. APIs to configure timeouts and a policy flag to disable retries.
