### ISSUE TITLE
Certificate Pinning. What about analytics, maps etc?

### ISSUE THREAD

**Issue by iTwenty** [square/okhttp#1846]
[I had asked this question on SO, but got no responses there](http://stackoverflow.com/questions/32221615/ssl-certificate-pinning-in-android-app-that-uses-maps-play-services-analytics)

I have been doing a fair bit of reading about preventing man in the middle attacks on my app using tools like Charles, Fiddler, mitm etc. I like the idea of pinning my server's SSL certificate since that means all other certs will throw an error.

But, the app uses libs like google maps, play services, analytics tools etc which must have their own SSL certs. Does it mean that I would need to manually pin the certs of all these libs too?

**Comment by artem-zinnatullin** [comment]
Answered on SO.

>But, the app uses libs like google maps, play services, analytics tools etc which must have their own SSL certs. Does it mean that I would need to manually pin the certs of all these libs too?

In short: **no**, because you apply `CertificatePinner` to your instance of `OkHttpClient` and it affects only those connections which pass through this instance of the client. 

Libraries such as Google Maps, Play Services, etc usually don't allow you to set your `OkHttpClient`, so you can not affect their HTTP connections (though it's possible via reflection in some cases).

**Comment by iTwenty** [comment]
Alright. That makes sense. Thanks for clarifying the doubt!
