### ISSUE TITLE
RequestBody Content Length is always '2'

### ISSUE THREAD

**Issue by stoyicker** [square/okhttp#1864]
Creating a request body does not seem to properly understand its size. 
See http://stackoverflow.com/questions/32647760/okhttp-requestbody-returning-wrong-content-length/32664465#32664465 for context.

MNWE: https://github.com/stoyicker/okHttpContentLength2Bug - Run the unit test.

Might be related to #1857 ?

**Comment by swankjesse** [comment]
My guess is Retrofit isn't treating the request body as special, which means Gson is converting it to a string. Whenever you convert an interface to JSON you get `{}` because Gson doesn't know about any fields.

Should Retrofit treat RequestBody as special? Probably. Mind opening a bug with that project? Thanks.
