### ISSUE TITLE
Socket SO_SNDBUF size too big for some networks

### ISSUE THREAD

**Issue by pwerry** [square/okhttp#1925]
We've discovered a puzzling issue with `WebSockets` (and perhaps `Sockets` in general) on Android. Under certain circumstances that are not fully understood, writing a large buffer to a `Socket` with a `SO_SNDBUF` size greater than the MTU of the node directly upstream of the device *may* result in that upstream node dropping packets. If you write chunks to the `Socket` in sizes less than the upstream MTU it's not a problem. Our working theory is that the OS is unable to resolve the MTU using PMTUD, even though the router is correctly returning "fragmentation required" responses when the DF bit is set (we tested a few ICMP packets to the router). Flushing the underlying `OutputStream` associated with the `Socket` after writing each `Segment` doesn't seem to accomplish much if the total bytes written across all segments is larger than the MTU. The only solution we've been able to find so far is to call `Socket#setSendBufferSize(int)` with a value less than the MTU (1024 seemed reasonable given that the upstream MTU in our case was 1492). 

A few caveats and interesting data points:
- Not all upstream nodes behave this way. In fact we have only been able to reliably replicate the issue using a certain router on a certain network
- A router involved in replicating the issue actually did send back packet fragmentation errors when hit with ICMP DF packets
- The standard MTU on Android is 1500, the standard `SO_SNDBUF` size is 512KB
- Android always seems to report an MTU of 1500 even when the upstream MTU is smaller
- The frequency of this issue in the wild is statistically significant, at approximately 10% of all users. It is especially prevalent in emerging markets like Nigeria, Ghana, and India. 
- We can confirm this affects devices running Lollipop, and we estimate it affects devices running KitKat as well. Marshmallow hasn't been tested yet
- It affects a wide range of devices across many manufacturers, implying the issue is probably not manufacturer specific
- This seems to be a problem with the OS rather than with okhttp, but there might be something okhttp can do to reduce the impact of the issue

Just to test the waters, what appetite would there be for adding an API to `OkHttpClient` to expose a configurable `SO_SNDBUF` size?

**Comment by swankjesse** [comment]
FYI @nfuller

**Comment by nfuller** [comment]
I'll ask and see if anyone on the Android connectivity team has seen anything like it.

@pwerry
Can you provide any more specifics? Network traces, manufacturers of network and android devices, network configuration? It might help track down reports or eventually repeat it.

**Comment by diegomontoya** [comment]
@pwerry If upstream is 1492, why are you using 1024 instead of something closer to 1400?

**Comment by swankjesse** [comment]
Right now you'll have to use `SocketFactory` to get what you want. I think the best solution is to fix this in the underlying operating system.

Any advice on any defaults we should use in OkHttp? I'm reluctant to change the global default.

**Comment by nfuller** [comment]
FYI - we're looking at this bug on the Android side right now.

Current thinking is that the change to the default segment size (https://github.com/square/okio/commit/f30955cb15eb234f874dd55819686832c960765b) triggered it: the client is more likely to construct a packet that is larger than the actual MTU of the network.

**Comment by nkzawa** [comment]
+1

**Comment by swankjesse** [comment]
I doubt the increased segment size triggered this; that change hasn't been released yet.

**Comment by swankjesse** [comment]
Unclear if there’s an action for us to take on this.

**Comment by nfuller** [comment]
Just a comment regarding the Android issue I referenced above (the segment size suggestion). We believe that it has turned out to be a combination of:

1) Increased segment size means the outgoing packet size became larger and was close to the MTU (due to buffer array passed to the write being larger). Previously the packets were not that close to the MTU.
2) The carrier was doing some header injection, thus increasing the packet size *beyond* the MTU and causing the packet transmission to fail (and for it to be resent, exactly as it was before....).

Something to look out for / be aware of, perhaps. Not an OkHttp problem at all, of course.

**Comment by diegomontoya** [comment]
@nfuller We are running into this issue and causing a great deal of headache to debug. Is there something that devs can do right now to mitigate this problem on android side?

**Comment by nfuller** [comment]
@diegomontoya can you be more specific? What are you actually seeing?

My comments above can be summarized as "I've seen something similar I can't explain on Android" followed by "Never mind, we discovered a carrier was doing invalid things to packets on their network which increased the size of a valid packet so it was no longer valid". The carrier stopped doing it when we pointed it out.

AFAIK we have no evidence on the Android side of the MTU being ignored. The information in the original report above ("certain router on a certain network") wouldn't be enough to reproduce the issue to understand the cause.

I suspect the "make the buffer size smaller" fix described has the _side effect_ of shrinking the packet size so if there is an MTU issue I can see why it might improve things. That may not be guaranteed, though, if there are buffers lower in the stack (not sure what setting SO_SNDBUF actually guarantees and whether it's treated as a "hint" rather than an order).

If you can capture a "smoking gun" tcp trace file (e.g. using tcpdump on a _rooted_ or userdebug build device) you can send it to me or analyse it yourself in wireshark. I'll pass it on to the Android networking folks and ask them to take a look if something is clearly wrong.

You can look at http://www.androidtcpdump.com/ if you need to create / obtain tcpdump binary to run on a device. I'm afraid I can't guarantee the safety of the binary or source because AFAIK it's not produced / maintained by Google so you use it at your own risk, no warranty implied, etc.
