### ISSUE TITLE
i wanna the progress of uploading a file

### ISSUE THREAD

**Issue by lizhangqu** [square/okhttp#1928]
see this file [UploadProgress.java](https://github.com/aried3r/okhttp/blob/dc98121808af528c47f46329a1af72bbe5d06ddc/samples/guide/src/main/java/com/squareup/okhttp/recipes/UploadProgress.java)

but i found the progress is not the real progress. the callback progress is the progress that the file writes to the memory.if i upload a file ,after the progress finished,i will wait the same time(the time the progress spend) again to get the response from server .Is there any solution ?

**Comment by goncalossilva** [comment]
You should call `flush` on the `sink` after every call to `write` to ensure this doesn't happen. It might fix your issue.

One problem I have with this though is that I see the progress bar going up twice, once fast and another one slower. I assume OkHttp is caching the file locally before uploading it... but there's no clear way to know when it is just caching internally or actually uploading. I'd also love to be able to disable this as (for other reasons) we already copy the file locally, so this essentially means there are 3 copies of the given file while uploading.

**Comment by swankjesse** [comment]
The underlying problem is we don't have a mechanism for the peer to acknowledge received writes. That _might_ be hackable with window size on HTTP/2, but even that would be unreliable.

What we're expecting is that for large uploads, eventually the buffers will fill up and the write calls will block. At that point the upload progress should be pretty accurate.

Closing because there's no clear action to take here.

**Comment by goncalossilva** [comment]
@swankjesse What about the file being written twice? Any clues about that and how it can be distinguished?
