### ISSUE TITLE
Why does Request not have an equals function?

### ISSUE THREAD

**Issue by jadekler** [square/okhttp#1973]
Is this intentional? If not, I'm happy to PR. Makes testing much harder without it. The following, for example, does not work:

```
verify(okHttpClient).newCall(expectedRequest); // verify = mockito
```

**Comment by swankjesse** [comment]
Request equality is reference equality. This is necessary because requests are stateful objects; the request body is mutable. Making say, `GET` requests equal is possible, since they wouldn't share headers. But also potentially flaky, because of non-semantic details like ordering of headers.

It's worth consideration.

**Comment by jadekler** [comment]
@swankjesse It would help testing quite a bit. Without it, testing okHttp connectors **requires** argument captors (which let you dig into the request body after the call, get the buffer, and read the body). It's a little painful.

Perhaps an equals function that has verbose documentation around its stateful nature?

Also, worth noting that children objects would need equals, too (I can't remember which, but I noticed things like Header / RequestBody / something like those also lacked equals).

**Comment by swankjesse** [comment]
Putting this in the icebox only because I have no idea how we'd define equality on these.

**Comment by swankjesse** [comment]
No plans to implement this.
