### ISSUE TITLE
SocketTimeoutException occured while I upload a big file,

### ISSUE THREAD

**Issue by huxq17** [square/okhttp#2060]
W/System.err: java.net.SocketTimeoutException: timeout
12-03 16:55:10.233 24888-25042/com.andbase.demo W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
12-03 16:55:10.233 24888-25042/com.andbase.demo W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
12-03 16:55:10.233 24888-25042/com.andbase.demo W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:158)
12-03 16:55:10.233 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
12-03 16:55:10.233 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:46)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:46)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at okio.ForwardingSink.write(ForwardingSink.java:35)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at com.andbase.demo.http.request.CountingRequestBody$CountingSink.write(CountingRequestBody.java:72)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
12-03 16:55:10.234 24888-25042/com.andbase.demo W/System.err:     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:104)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.RequestBody$3.writeTo(RequestBody.java:118)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeOrCountBytes(MultipartBuilder.java:277)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeTo(MultipartBuilder.java:297)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.andbase.demo.http.request.CountingRequestBody.writeTo(CountingRequestBody.java:57)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:890)
12-03 16:55:10.235 24888-25042/com.andbase.demo W/System.err:     at com.andbase.demo.http.OKHttp$RedirectInterceptor.intercept(OKHttp.java:67)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:867)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:748)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:277)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
12-03 16:55:10.236 24888-25042/com.andbase.demo W/System.err:     at com.andbase.demo.http.OKHttp$NetWorkTask.onRun(OKHttp.java:240)
12-03 16:55:10.237 24888-25042/com.andbase.demo W/System.err:     at com.andbase.tractor.task.Task.run(Task.java:73)
12-03 16:55:10.237 24888-25042/com.andbase.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-03 16:55:10.237 24888-25042/com.andbase.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-03 16:55:10.237 24888-25042/com.andbase.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-03 16:55:10.237 24888-25042/com.andbase.demo W/System.err: Caused by: java.net.SocketException: Socket closed
12-03 16:55:10.238 24888-25042/com.andbase.demo W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at libcore.io.Posix.sendto(Posix.java:211)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:509)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
12-03 16:55:10.239 24888-25042/com.andbase.demo W/System.err:     at okio.Okio$1.write(Okio.java:80)
12-03 16:55:10.240 24888-25042/com.andbase.demo W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
12-03 16:55:10.240 24888-25042/com.andbase.demo W/System.err: 	... 26 more

I'm in trouble because the error happened many times, What should I do?

**Comment by huxq17** [comment]
mOkHttpClient.setRetryOnConnectionFailure(true);
mOkHttpClient.setConnectTimeout(15, TimeUnit.SECONDS);
mOkHttpClient.setReadTimeout(15, TimeUnit.SECONDS);
 mOkHttpClient.setWriteTimeout(15, TimeUnit.SECONDS);
This's my configuration

**Comment by huxq17** [comment]
Chinese:当我上传打文件的时候，非常容易遇到socketTimeout异常，我该怎么做？

**Comment by swankjesse** [comment]
Could you provide an executable test case?

**Comment by huxq17** [comment]
I think the reason is the network is not good

**Comment by dudhatparesh** [comment]
Guys I am having same issue.
Here are my exception logs.

java.net.SocketTimeoutException: timeout
W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:158)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:46)
W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:286)
W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:52)
W/System.err:     at okhttp3.RequestBody$1.writeTo(RequestBody.java:71)
W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:704)
W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.net.SocketException: Socket closed
W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
W/System.err:     at libcore.io.Posix.sendto(Posix.java:176)
W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:553)
W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:513)
W/System.err:     at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:42)
W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:271)
W/System.err:     at okio.Okio$1.write(Okio.java:80)
W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
W/System.err: 	... 19 more


My use case is quite simple i just want to upload image as bas64 to server. Image is captured through camera.
