### ISSUE TITLE
Takes time to cache response

### ISSUE THREAD

**Issue by iamshajeer** [square/okhttp#2061]
Hi,
I am using okhttp response caching mechanism. I am not getting header from server, so I had created an interceptor for that, and it works perfectly. the problem is, server response comes within 10-11 seconds. and the response size is around 1.5 MB. but it takes around 25 seconds to write the cache, and to get call the success method. how do I improve this ?

**Comment by swankjesse** [comment]
Tough question. Most devices can write to local storage much much faster than 60 KB/s. Perhaps fix your device?

**Comment by iamshajeer** [comment]
but if I remove caching then it loads faster.

**Comment by swankjesse** [comment]
Any ideas on what we should do?

**Comment by iamshajeer** [comment]
caching (writing to cache) can be done asynchronously.

**Comment by swankjesse** [comment]
@iamshajeer unfortunately, async caching requires an in-memory buffer. How big is that buffer? If it’s large we have a problem, if it’s small we aren’t making large downloads faster. Also need to coordinate between concurrent downloads to we don’t exhaust the heap. I really think the fix to this problem is to fix the local disk.
