### ISSUE TITLE
What is OkHttp3 new proguard rules?

### ISSUE THREAD

**Issue by lzy26fate** [square/okhttp#2230]
-dontwarn com.squareup.okhttp.**
-keep class com.squareup.okhttp.** { *;}
-dontwarn okio.**
this is old version proguard rules

**Comment by JakeWharton** [comment]
Change `com.squareup.okhttp` to `okhttp3` in each.

**Comment by ThomasSunderland** [comment]
Question: Isn't there an asterisk missing before the semicolon in the line... 

`-keep class com.squareup.okhttp.** { ;}`

**Comment by getintouchapp** [comment]
@ThomasSunderland 

Yes that's correct. It should be

```
-keep class com.squareup.okhttp3.** {
*;
}
```

**Comment by swankjesse** [comment]
(The package name is `okhttp3` with no `com.squareup` prefix.)

**Comment by wingsum93** [comment]
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**


it is all corect for okhttp3

**Comment by JakeWharton** [comment]
Those rules are massively over matching. As far as I can tell you don't
need any ProGuard rules for OkHttp.

**Comment by mfaust35** [comment]
I do get warnings using OkHttp3 & ProGuard :
(with gradle : compile 'com.squareup.okhttp3:okhttp:3.2.0' & compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0') 
```
Warning: okhttp3.internal.huc.HttpsURLConnectionImpl: can't find referenced method 'long getContentLengthLong()' in program class okhttp3.internal.huc.HttpURLConnectionImpl
Warning: okhttp3.internal.huc.HttpsURLConnectionImpl: can't find referenced method 'long getHeaderFieldLong(java.lang.String,long)' in program class okhttp3.internal.huc.HttpURLConnectionImpl
```
Which is "kind of normal" since in package [okhttp3/internal/huc](https://github.com/square/okhttp/tree/okhttp_32/okhttp-urlconnection/src/main/java/okhttp3/internal/huc) on branch `okhttp_32`, the class HttpsURLConnectionImpl.java has some strange code line 75 : method `getContentLengthLong()` exist neither in `HttpURLConnectionImpl.java`, nor in `DelegatingHttpsURLConnection.java`.
It may be related to this [other issue](https://github.com/square/okhttp/issues/673)?

Anyway, in my case, ignoring these 2 warnings with `-dontwarn okhttp3.internal.huc.HttpURLConnectionImpl` seems to be sufficient. I do get some other warnings with okio though (about some classes in package java.nio.file).

**Comment by peterbetos** [comment]
Here's the correct format:

```
-keepattributes Signature
-keepattributes Annotation
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
```

**Comment by JakeWharton** [comment]
Those rules are crazy. You might as well just turn off ProGuard if you're
going to keep 100% of libraries.

**Comment by mirmousaviii** [comment]
I use dontwarn and pass the build signed apk, But my application in signed mode (release) every time run onFailure from Callback.

**Comment by BoD** [comment]
Just as a courtesy to people finding this page (for some reason it's the first result when googling for okhttp proguard), the official rules are here:
https://github.com/square/okhttp#proguard

**Comment by GeraldoLimaGlance** [comment]
Hi everyone, I'm still facing such errors and I tried every possible configuration I found on the official pages.

Here's the error:  `java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient$Builder;`

and here's my last configuration attempt (including Retrofit's in case it matters somehow):

```
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepattributes *Annotation*

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
-keepclassmembernames interface * {
        @retrofit.http.* <methods>;
}
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep class okio.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
```

Does anyone know what might be missing?
