### ISSUE TITLE
[Websocket] Configure frame size to avoid payload splitting.

### ISSUE THREAD

**Issue by rdtorres** [square/okhttp#2270]
Before version 2.5 of okhttp-ws, client was passing a **Buffer** and it was sent as specified by the client.

On version 2.6, the implementation migrated to use **RequestBody** and **ResponseBody**. By doing this all payload sent to server are truncated at 2048 (size of the **Segment**). If the payload is bigger than 2048, then the implementation sends the remaining data as a continuation frame.

According to [RFC](https://tools.ietf.org/html/rfc6455#page-27), there is nothing wrong by splitting the payload into multiple frames.

But in my opinion this splitting is unnecessary and it should have an option to define the max desired frame size to avoid splitting.

**Comment by swankjesse** [comment]
We can probably fix this without much hassle.

**Comment by JakeWharton** [comment]
Your analysis isn't quite correct. 

Given a 10000 byte string:
```
  @Test public void blah() throws IOException {
    String foo = "";
    for (int i = 0; i < 1000; i++) {
      foo += "1234567890";
    }
    client.sendMessage(RequestBody.create(TEXT, foo));

    System.out.println(client2Server.buffer.readByteString(4).hex());
  }
```
The header of the first frame is `01fe2000` which says that its length is 8192. The largest multiple of complete segments is taken and emitted in this case. Because of how `RequestBody` works, we can never know which write is the last one, so additional bytes are buffered. In this case, `close` is called immediately after which flushes the remaining bytes in another frame.

At most you'll see two frames for the fully-buffered case.

In addition to unifying the buffered and streaming model, this behavior has other benefits such as allowing pings and pongs to interleave without having to wait for potentially slow message sources (like the file system).

As you note, the RFC allows this, and it should be completely transparent to the receiver. Are you experiencing a bug or performance anomaly because of this behavior?

**Comment by rdtorres** [comment]
@JakeWharton  You are correct. Initially I tested it using a payload of 2835 bytes, the request was divided in one frame of 2048 and the subsequent frame of 787. After your comment, I experimented increasing the payload size and I could verify that the first frame is a multiple of 2048 (`Segment` size) and "the remaining" is sent as a separated continuation frame.

In my particular case, I faced an issue on the receiver because I have a proprietary protocol on top WebSocket that expect the full message to be self contained in one frame. So treat this ticket as a feature request instead of a bug. 

I disagree with this comment :
> Because of how `RequestBody` works, we can never know which write is the last one

The WebSocket implementation could potentially use `RequestBody#contentLength()` to identify the last write. In case it returns -1, then your statement is correct. But this can still have the problem of slow message sources as you identified. My suggestion is that we could potentially have `setSendBufferSize(int)` along the same line of thought as `Socket#setSendBufferSize(int)`

**Comment by JakeWharton** [comment]
Ideally we could optimize for the buffered case, but Okio makes it hard. I'm not sure that _just_ a known content length should be enough to trigger buffering since you could easily have a known length from a multi-gigabyte file!

We should figure something out for already-buffered types though for your case. Those where you've used a `String`, `byte[]`, or `ByteString` and the data is already in memory. Ideally this would work without the need to hand-customize some size.
