### ISSUE TITLE
Access raw ResponseBody Source

### ISSUE THREAD

**Issue by Idhor** [square/okhttp#2274]
Is there a way to access the raw response body source without automatic unzip and unchunk?

**Comment by swankjesse** [comment]
No.

**Comment by Idhor** [comment]
Any chance that this will be flagged as an enhancement? I was thinking to something like `response.body().rawSource()`, in my use case is useful
I'm developing an http server with some proxy behavior and i'm using Okio to work with streams and i would like to use Okhttp to do the "real" requests and then forward the body without chunk and gzip again

**Comment by swankjesse** [comment]
Sorry, that use case is a special snowflake and unlikely to be useful for anyone else! Particularly since it won't work for HTTP/2, which should have a majority of web traffic within a few years anyway.

Please fork the project; the simplest solution to your problem is going to probably require that anyway.
