### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by ppamorim** [square/okhttp#2488]
Hi Square.

I forked this library with the objetive to translate the website, I translated my fork to Portuguese (it was simple!) and I have plans to translate to another languages (Spanish, German and Chinese).

Do you have any interest on this feature?

Thanks.

**Comment by JakeWharton** [comment]
My hesitation would be that we have no way to maintain the translations
over time as the content changes.

**Comment by ppamorim** [comment]
The last change of the website was 4 months ago. I cannot see any problem with that.

**Comment by swankjesse** [comment]
Although I like this idea it grows the amount of stuff we’re responsible for.

I’m not currently prepared for the extra responsibility of additional languages in any official capacity. It is nice because it is inclusive, but it is not nice because it suggests things that I do not want to suggest In particular it implies we’ll be able to support issue reports in non-English languages, which we cannot do.

Please do write about OkHttp in all of the languages you know! But I don’t want to include them in the project itself.
