### ISSUE TITLE
No ability to use a supported (but not enabled) cipher suite

### ISSUE THREAD

**Issue by emilburzo** [square/okhttp#2698]
Follow-up to #2694

After a day of debugging I found out the root cause of the issue.

The issue can be traced back to commit f695ea7.

Specifically, the change from

```
sslSocket.getSupportedCipherSuites()
```

to 

```
sslSocket.getEnabledCipherSuites();
```

While I understand the motivation, and it should be good in practice, on this particular device it's actually a downgrade in functionality, because it can't be used with modern ciphers (specifically, the ones from [cipherli.st](https://cipherli.st/), nginx section)

Here are the `TLS_` supported cipher suites:

```
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DH_anon_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_DSS_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_DH_anon_WITH_AES_256_CBC_SHA
```

And here are the `TLS_` enabled cipher suites:

```
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_DSS_WITH_AES_128_CBC_SHA
```

And my server supports the following:

```
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
```

The last one (`TLS_DHE_RSA_WITH_AES_256_CBC_SHA`) being the common ground.

I'm not sure what would be the best way to fix it, maybe a flag to let the user choose if he wants the supported cipers or the enabled ones?

What kind of issue is this?
- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
     something, or to understand why something isn't working the way you expect it to, use Stack
     Overflow. https://stackoverflow.com/questions/tagged/okhttp
- [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
     get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed
- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
     already exists! Don’t send pull requests to implement new features without first getting our
     support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
@nfuller thoughts?

**Comment by swankjesse** [comment]
Thanks for the fantastic investigation. For anyone following along, here’s the original PR:
https://github.com/square/okhttp/pull/1208

If you’re looking for a quick workaround, you can build your own SslSocketFactory that uses your own business logic to determine which suites are enabled.

**Comment by nfuller** [comment]
I think we discussed putting the "enabled" vs "supported" behavior behind a setting but it was decided not to do it because it would complicate the API.

I still think the "use enabled" behavior makes most sense on the Android platform and as the safe default for the library, but I do see that people that value connectivity over other considerations might want to alter it to "use supported".

I'd be happy with any change providing we retained the ability to make it "use enabled" in the Android platform.

**Comment by swankjesse** [comment]
@nfuller what if we flip OkHttp to use any supported cipher suite, and the Android platform just declares ConnectionSpec instances to match its needs? Would that work?

**Comment by nfuller** [comment]
@swankjesse If I'm interpreting what you're suggesting correctly: not really.

We don't want to be explicit about the ciphers to use because the whitelist we rely on *is* the set of enabled ciphers. On the Android platform, the SSLSocketFactory can be replaced with a new one at runtime by apps or GMS core that may (for example) disable a cipher and introduce a new one. If we baked a list of ciphers into the HttpsHandler code that builds the ConnectionSpec (which is not replaceable and ships with the device) we would continue using the disabled cipher (we don't immediately drop _support_ for ciphers, just disable them by default if they're found to be insecure) and would not use the new cipher because it wouldn't be in the hardcoded whitelist (because we can't predict what ciphers may be added in future that won't be broken).

This is the reason why on Android so far we use "null" with OkHttp to mean "just use the set the SSLSocket has enabled, it may know better than you do".

**Comment by swankjesse** [comment]
BTW, @emilburzo you can work around the problem by manually configuring the supported cipher suites on the target device. Lousy workaround, but it’ll at least restore connectivity.

**Comment by emilburzo** [comment]
@swankjesse for now I forked okhttp 2.7.5 and changed `sslSocket.getEnabledCipherSuites()` back to `sslSocket.getSupportedCipherSuites()`

My reasoning being that since I only use secure/modern ciphers server-side, the intersection between `client supported` and `server supported` should never result in an insecure one being used.

And at least on this (really old) device, it means being able to use the only modern/secure cipher that is supported, but not enabled.

**Comment by swankjesse** [comment]
We should probably at a minimum document this because customizing the SSLSocketFactory is tricky work.
