### ISSUE TITLE
Replace IllegalStateException by IOException, SecurityException etc. where possible

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#2934]
okhttp seems to throw IllegalStateException quite often, for instance when unexpected data is received (see
https://github.com/square/okhttp/issues/2683).

Please consider replacing all IllegalStateExceptions by
- IOException when unexpected network traffic occurs (for instance, HTTP2 frame errors etc)
- SecurityException for TLS errors etc.

The IllegalStateExceptions cause apps using okhttp to crash unexpectedly and as far as I know, IllegalStateExceptions should only be thrown when an API is called incorrectly (for instance, sending a request before it was specified or something like that).

**Comment by swankjesse** [comment]
Yes, we only intend to throw IllegalStateException on mistakes made by the API user, not on mistakes made by the remote peer. If you have particular examples, I can fix ’em.

**Comment by rfc2822** [comment]
For instance, I got this crash:

```
Caused by: java.lang.IllegalStateException: closed
	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:374)
	at okio.Buffer.writeAll(Buffer.java:993)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
```

I never closed a connection twice or something like that, at least not intentionally. Wouldn't it be better to use IOException for that? For instance, `Socket bind()` throws an `IOException` too, if the socket is already bound.

I suggest to replace almost all IllegalStateExceptions, especially

`IOException` could be used here:

* `src/main/java/okhttp3/internal/connection/RealConnection.java` ("already connected")
* `src/main/java/okhttp3/internal/connection/StreamAllocation.java`
* `src/main/java/okhttp3/internal/http1/Http1Codec.java`
* `src/main/java/okhttp3/internal/http1/Http1Codec.java` (for instance, the invalid states)
* `src/main/java/okhttp3/internal/tls/DistinguishedNameParser.java` ("Unexpected end of DN", this really shouldn't be an unchecked exception)
* `src/main/java/okhttp3/internal/cache2/Relay.java` ("closed")
* `src/main/java/okhttp3/internal/http2/Http2Connection.java`
* `src/main/java/okhttp3/internal/http2/Http2Stream.java` (for instance, when response headers are already sent)

Something like `URISyntaxException` could be used here:
* `src/main/java/okhttp3/HttpUrl.java` (it can easily happen that you build an URL from parts you have received from somewhere; no unchecked exception should occur when you innocently build an URI from such parts)
* `src/main/java/okhttp3/Response.java` (see above)

`SecurityException` could be used here:
* `src/main/java/okhttp3/Handshake.java` ("cipherSuite == null")
* `src/main/java/okhttp3/OkHttpClient.java` ("Unexpected default trust managers:" etc.)

**Comment by swankjesse** [comment]
Looking through most of these it seems like almost all of ’em are caused by clients using the API improperly. For example, it’s not good if a client attempts to read a stream after it has been closed. I’m not sure how you got in that situation, but that’s what we should fix.

The DN example is definitely one we should fix. I’m happy to fix any others that could be triggered by a misbehaving server. But if your client code calls APIs out of sequence that needs to result in a hard exception. Otherwise bugs don’t get fixed!

**Comment by rfc2822** [comment]
> I’m not sure how you got in that situation, but that’s what we should fix.

I don't have an idea where to begin. The code works in 99,9999% of the time – we have only got a single report, and I guess that it's related to a server/proxy which sends unexpected data (and maybe closes a stream two times or whatever, I don't know it). I doubt that it's caused by incorrect API usage, but if you say so, I'll believe it and just ignore this problem until it happens more often.

**Comment by swankjesse** [comment]
I looked into the unchecked exceptions thrown by the DistinguishedNameParser.

It should be impossible for DistinguishedNameParser to throw those exceptions if the input is always a well-behaved X500Principal. The correct behavior is to continue to throw unchecked exceptions here (because they indicate bugs) rather than checked IOExceptions (because they indicate connectivity or protocol problems).

As for the unexpected IllegalStateException, I’d love a testcase.

No further action to take on this.

**Comment by filipatbnp** [comment]
What is X500Principal?
