### ISSUE TITLE
DISCARD_STREAM_TIMEOUT_MILLIS should be configurable

### ISSUE THREAD

**Issue by modislaszlox2** [square/okhttp#3056]
I'm using https://github.com/amitshekhariitbhu/Fast-Android-Networking(which uses okhttp) to prefetch some data. 
Prefetch consumes the stream by calling close() but because of DISCARD_STREAM_TIMEOUT_MILLIS larger data is not downloaded(same issue with slower network and smaller data).

**Comment by swankjesse** [comment]
Consider reading the stream fully by calling `body().source().skip(Long.MAX_VALUE)`.

**Comment by ericvdmaarel** [comment]
I have this problem with a client using reftrofit2 which uses okhttp (version 3.8.0). When closing the ResponseBody (or actually an InputStream retrieved from it) an exception is raised server side. Setting HttpCodec.DISCARD_STREAM_TIMEOUT_MILLIS to 300 (instead of 100 from the distribution) solves the problem. This suggests that it takes more time than the allowed 100ms to clean up the socket and close it or return it to the pool, where 300ms suffices.
However, doing the skip as suggested (and handle the EOFException that gets raised), with the standard value of 100 for HttpCodec.DISCARD_STREAM_TIMEOUT_MILLIS also works.
