### ISSUE TITLE
Formalize Connection Pool locking policy.

### ISSUE THREAD

**Issue by dave-r12** [square/okhttp#3063]
https://github.com/square/okhttp/issues/2986 mentions adding some documentation around the locking policy for Connection Pool. There is a page on the wiki that outlines the policy for HTTP2 that is very helpful for new readers of the code base. I think a similar document would be helpful for the Connection Pool, in addition to the reasons listed on the referenced issue.

**Comment by swankjesse** [comment]
I’d love to bring these classes closer together somehow. We need all three ’cause they all have different lifetimes.

Creating multiple locks would be worthwhile if it’d increase throughput. Otherwise multiple locks are bad ’cause you can deadlock. And cause you spend more time in aggregate locking and unlocking.

One really important part of the design is we never do I/O – not even socket close – with a lock held. That’s intended to prevent contention.

**Comment by dave-r12** [comment]
Gotcha, thanks for the insight. I like the current arrangement of things here. Unless you feel differently, I do not think it's valuable to change anything. It seems like the only things to call out in the docs:

- A single lock is used to guard the state of ConnectionPool, RealConnection and StreamAllocation.
- The lock is the ConnectionPool instance.
- Never do I/O while holding the lock to prevent contention.
- Prefer the single lock to avoid deadlock and overhead of aggregate locking/unlocking that will occur with multiple locks.

**Comment by swankjesse** [comment]
Yep, that’s perfect.

**Comment by dave-r12** [comment]
I bolted on those notes to the concurrency page in the wiki. I also updated some of the class names in the http/2 section.

**Comment by swankjesse** [comment]
Further action on this?
