### ISSUE TITLE
HTTP2 Server Push - Feature Request

### ISSUE THREAD

**Issue by f3z0** [square/okhttp#3106]
It us my understanding that okhttp is persisting pushed streams to disk, accessible through the cache and not accessible via public API. I understand the appeal of maintaining a consistent protocol-agnostic interface and the motivation to be proactive against anti-patterns (e.g. using push when it's not appropriate). With that said however, I need to receive many pushes from a 3rd-party server and writing to disk is not an option. Looking at other mainstream http2 client libraries this is usually supported via a callback mechanism. I'd be happy to volunteer time to implement this functionality, using whatever design you deem appropriate. Thanks!

**Comment by swankjesse** [comment]
Just curious – which mainstream HTTP2 client libraries were you looking at?

I’m quite reluctant to do this because it opens the door to many other HTTP/2 features that will be necessary to adequately support this. In particular you’ll likely want the connection to stay open to accept pushes.

Have you considered websockets?

BTW, we haven’t yet implemented any support for HTTP/2 push, but it’s coming.

**Comment by swankjesse** [comment]
Tracking here:
https://github.com/square/okhttp/issues/607
