### ISSUE TITLE
Why OkHttpURLConnection 3.6.0 not supporting interceptors?

### ISSUE THREAD

**Issue by laaptu** [square/okhttp#3254]
[ ] Question
   * I am using OkHttpURLConnection 3.6.0 ( OkHttpClient 3.6.0) with Volley 1.0.0
   * I need to use [OkHttp interceptors](https://github.com/square/okhttp/wiki/Interceptors) in my application.
   * I have browsed the source code of [OkHttpUrlConnection](https://github.com/square/okhttp/blob/master/okhttp-urlconnection/src/main/java/okhttp3/internal/huc/OkHttpURLConnection.java) and at line 383, the OkHttpClient interceptors are cleared out.
  * Is it by design? Commenting that line makes the added interceptors work. Should we not use interceptors with OkHttpURLConnection? 
  * At this [interceptor wiki link](https://github.com/square/okhttp/wiki/Interceptors), it is saying that interceptor doesn't work with OkURLFactory ( which is deprecated now). Does it mean it won't work with OkHttpURLConnection as well?

**Comment by swankjesse** [comment]
Yep, this is by design. Interceptors have never worked with HttpURLConnection. It might be possible to make ’em work, but we haven’t considered the consequences. I’m also anxious that supporting interceptors there might make certain types of bug fixes more difficult.

I’d like to encourage you to use the Request/Response API instead. There’s some open source projects that might make it easier to migrate.
https://github.com/lxdvs/Volley-OkHttp-Android

**Comment by laaptu** [comment]
@swankjesse Thanks Jesse. I will use the Request/Response API instead.

**Comment by luhaikong** [comment]
I'm so sorry to see that.

**Comment by xckevin** [comment]
oh, we need the feature 😢 pls support it

**Comment by swankjesse** [comment]
You can use this:
https://gist.github.com/swankjesse/dd91c0a8854e1559b00f5fc9c7bfae70

**Comment by swankjesse** [comment]
(you’ll need to comment out lines 570 and 572)
