### ISSUE TITLE
Streaming request body does not produce error immediately

### ISSUE THREAD

**Issue by ming13** [square/okhttp#3320]
Seems like if there is some socket issue during streaming `POST` it does not indicate it immediately, but waits for _some_ buffer to be filled up. Is it possible to reduce this buffer somehow or change this behaviour to fail as soon as possible? Unfortunately I failed to find the exact reason of this.

The code and steps to reproduce are below.

### Client

```kotlin
import okhttp3.*
import okio.BufferedSink
import java.io.IOException
import java.util.concurrent.TimeUnit

fun testStreamingRequestBodyWhenConnectionIsBeingBrokenInFlight() {

    class StreamingRequestBody : RequestBody() {
        override fun contentType() = MediaType.parse("application/json; charset=utf-8")

        override fun writeTo(sink: BufferedSink) {
            while (true) {
                val messageSize = 1_000_000

                sink.writeUtf8("0".repeat(messageSize))
                sink.flush()

                Thread.sleep(TimeUnit.SECONDS.toMillis(1))
            }
        }
    }

    val request = Request.Builder()
            .url("http://10.0.2.2:8080/path")
            .post(StreamingRequestBody())
            .build()

    OkHttpClient().newCall(request).enqueue(object : Callback {
        override fun onResponse(call: Call, response: Response) {
            println("HTTP: success")
        }

        override fun onFailure(call: Call, e: IOException) {
            println("HTTP: failure")

            e.printStackTrace()
        }
    })
}
```
### Server

```python
#!/usr/bin/env python2

from SocketServer import StreamRequestHandler, TCPServer

class SilentHandler(StreamRequestHandler):
    def handle(self):
        print("Connection from: {}".format(self.client_address))

        for line in self.rfile:
            print("Message from client")


if __name__ == "__main__":
    serv = TCPServer(('', 8080), SilentHandler)
    serv.serve_forever()
```

## Steps

1. Start a server on a PC.
2. Start a client on an emulator.
3. Server should print some messages.
4. Kill the server.
5. Wait for about to 15 messages to be sent from the client and observe the following exception. Please take a notice that if you change `messageSize` from `1_000_000` to something like `10` it will take much, much longer — this is the exact issue of mine, I want to get this exception ASAP.

```
HTTP: failure
java.net.SocketTimeoutException: timeout
     at okio.Okio$4.newTimeoutException(Okio.java:227)
     at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
     at okio.AsyncTimeout$1.write(AsyncTimeout.java:183)
     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
     at okhttp3.internal.http1.Http1Codec$ChunkedSink.write(Http1Codec.java:325)
     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
     at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:53)
     at HttpKt$testStreamingRequestBodyWhenConnectionIsBeingBrokenInFlight$StreamingRequestBody.writeTo(http.kt:17)
     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
 Caused by: java.net.SocketException: Socket closed
     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:120)
     at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
     at okio.Okio$1.write(Okio.java:78)
     at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
 	... 25 more
```

## Versions

* OkHttp 3.7.0.
* Android 7.1.1.

**Comment by swankjesse** [comment]
You’re running into limits of the underlying protocol. Because the server doesn’t send an “I’m dead” message, the TCP uses timeouts to differentiate between a slow server and a dead server.

**Comment by ming13** [comment]
Yep, this is reasonable, but timeouts do not work properly in this case. If I modify the client code to use such configured client, nothing really changes and connection is not being closed after timeout passed.

```kotlin
val timeoutSeconds = 3L

val client = OkHttpClient.Builder()
        .connectTimeout(timeoutSeconds, TimeUnit.SECONDS)
        .readTimeout(timeoutSeconds, TimeUnit.SECONDS)
        .writeTimeout(timeoutSeconds, TimeUnit.SECONDS)
        .build()
```

The strange thing is and I see the issue with it — if the `messageSize = 10` it will take a very, very long time to exception to appear. If the `messageSize = 1_000_000` it will take about 15 seconds to appear. This lead me to the opinion that there is some inner buffer being overflown and only then the socket is being closed. Is it true or I am imagining something?

**Comment by swankjesse** [comment]
Yeah. OkHttp will buffer ~8 KiB of data before emitting it over the network. If you’re writing 10 bytes at a time it’ll take ~800 messages before anything is transmitted.

You can work around this by calling `flush()` to send the bytes to the outgoing socket immediately.

**Comment by ming13** [comment]
Yep, but I’m already flushing it in `StreamingRequestBody#writeTo`. Do you mean something else?

**Comment by swankjesse** [comment]
Hmm, that should be sufficient. Perhaps it’s buffering in a lower layer?

I’m not sure what action to take here. Maybe this is a bug in the emulator?

**Comment by pkhera** [comment]
This is answered at https://stackoverflow.com/questions/25962595/tracking-progress-of-multipart-file-upload-using-okhttp# however the solution there does not work for me. Let me know if it works for you. I might be missing something here.

**Comment by artem-zinnatullin** [comment]
@pkhera your link is about tracking of client → server request progress while this issue is about tracking connection issues asap for such requests.

**Comment by pkhera** [comment]
This could be related. The reason we do not get an immediate error is because it does not attempt to connect until the first byte is actually streamed. This may not happen until the Socket level buffer in not filled. If you created a custom SocketFactory that reduces the socket buffer size, you might get an immediate failure.

**Comment by wangjing53406** [comment]
@JakeWharton In my production environment also encountered a similar problem, a user in his wifi network request one of our AWS server API, the stability of the timeout, but other AWS server API normal access. So that change to use Volley to visit problem API is no such problem. Unfortunately I failed to find the exact reason of this.

okio.Okio$4.newTimeoutException(Okio.java:230)
okio.AsyncTimeout.exit(AsyncTimeout.java:275)
okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)


![image](https://cloud.githubusercontent.com/assets/8290623/26729154/2a788b62-47df-11e7-9837-a50407337c82.png)

![image](https://cloud.githubusercontent.com/assets/8290623/26729201/678aa7f6-47df-11e7-8a2a-8730936f8703.png)

**Comment by JakeWharton** [comment]
That's a normal timeout exception though

**Comment by swankjesse** [comment]
No action to take on this. If you’d like us to fix something, we respond to failing test cases.
