### ISSUE TITLE
Low bandwith & Large file Post causing readTimeout

### ISSUE THREAD

**Issue by NormanOu** [square/okhttp#3373]
Like closed issue #2443. I think I figure out why read timeout is firing but not write timeout.
Suppose we are running on a network with upload bandwidth 10KB/s and uploading a file larger than 1MB

I find out that Android Socket has a 512KB send buffer (at least on my phone it is), the problem lies here.
When okhttp finished flushing all the post data to the socket(which means the 512KB send buffer is full, but not all data is sent to the server), now the read timer starts count down.
Lets do some math here, 512KB / 10KBps, we need at lease 50s to send the data to server, not counting the time the server to calc and send back the response.
So, the time it take since okhttp done flush the last posting byte, till we got the first byte from server response, 1 minute read timeout would be considerable.

If we take consideration of networks even worst, like some 2G network with little bandwidth even to 2KB/s, then we need at least a read timeout of serveral minutes.

It seems the problem lies with the Socket send buffer. Really there's nothing more we can do in okhttp? It seems okhttp is hiding this send buffer tricky thing from us.

I think modifying the size of the Socket send buffer might be one direction for solving this problem, then maybe providing a nicer api for modifying Socket send buffer? So we can change set smaller send buffer under like 2G network? Or okhttp can detect the bandwith and help decide the proper send buffer size?

**Comment by swankjesse** [comment]
What action would you like us to take on this?

**Comment by NormanOu** [comment]
@swankjesse I've updated the issue, any ideas?

**Comment by swankjesse** [comment]
Thanks for updating the issue, I think I can see what’s going on. The network is really working, but its slow that OkHttp can’t tell from its layer. As far as OkHttp is concerned it wrote 512 KiB and nothing has happened since.

It’s also interesting that you’re seeing read timeouts. That means that OkHttp starts the clock on the response as soon as it finishes enqueueing the request. When there’s a big buffer locally that doesn’t work.

Sadly I don’t think there’s anything super smart we can do from our layer. Even if we disable the 512 KiB buffer in the local socket so that that write happens faster, there’s still a chance that there’s an equivalent buffer in the outgoing WiFi router or proxy. That is to say, that this network makes it  difficult to differentiate disconnected from slow.

What do other applications do in this case? I haven’t worked much with very slow networks and we can probably learn from smart people who have more experience with them.

**Comment by swankjesse** [comment]
No clear action for us to take on this.
