### ISSUE TITLE
Cancel concurrency issue

### ISSUE THREAD

**Issue by davidgyavol** [square/okhttp#3375]
We found an issue in the way `cancel()` is called on the `Call` after `onResponse()` is called on the callback:

Even after `onResponse` was called on our callback on a different thread,` cancel()` is still called from the main thread due to its concurrency nature - therefore `cancel()` calls `cancel()` on the `RetryAndFollowUpInterceptor` which calls `cancel()` on the `StreamAllocation` which we believe gets us in a state where we have a successful response with no body - `response.body().string()` returns null.

We believe that a fix for this might be to do a `return` in the `cancel()` method on the `RealCall` class if the `AsyncCall` delivered response to the callback.

**Comment by swankjesse** [comment]
We definitely intend to support canceling a request even if its body has been (partially) delivered. I’d like to write a test to confirm that the response body is never null if its response is canceled; that would be a horrible bug.

**Comment by swankjesse** [comment]
Looks like `CallTest.canceledAfterResponseIsDeliveredBreaksStreamButSignalsOnce()` already exercises this case. If you could provide an executable test case that demonstrates a null response body that’d be something we would act on immediately.

We support canceling a response even if its body has been (partially) delivered is so that you can avoid downloading and processing a large response object if you change your mind. Calling cancel() will cause that response body to throw an `IOException` which you can recover from gracefully. Use `Call.isCanceled()` if you want to differentiate between `IOExceptions` caused by local cancelation and those caused by other means.
