### ISSUE TITLE
Allow custom implementations of CertificatePinner

### ISSUE THREAD

**Issue by zergtmn** [square/okhttp#3389]
Hi.

We are in the process of implementing certificate pinning for our app and one of the requirements is to be able to update pins at any point while app is running.
Since both OkHttpClient and CertificatePinner are immutable to change pins we'd have to create a new instances of OkHttpClient and CertificatePinner containing the updated pins. Then we'd have to update all references to OkHttpClient in memory. Since we use Retrofit we'd have to update the reference to Retrofit instance and all references to cached Retrofit services as well (there are quite a lot of them in our repositories).
To me this approach seems unfeasible.

An another (possible) solution would be to allow CertificatePinner to be subclassed. That'd allow us to create a custom mutable CertificatePinner and set pins on it directly as needed without changing the OkHttpClient configuration.

WDYT?

**Comment by swankjesse** [comment]
Mutable CertificatePinners would cause a lot of additional complexity inside OkHttp. In particular we would have to tear down connection pooling because we couldn’t be confident that a pooled connection satisfies the current pins.

I think you should recreate your OkHttpClient when you create new pins.
