### ISSUE TITLE
onMessage() callback not work

### ISSUE THREAD

**Issue by S1owaway** [square/okhttp#3517]
My webSocket instance lives in sticky service. Sometimes on Meizu U10 (and on some other devices, even Samsung s7) after doze mode I try to send some bytes to socket (via WebSocket.send()) and no response. No onFailure, no onClosed, no onMessage (String and ByteString). Helps only restart the service.

**Comment by yschimke** [comment]
It is hard to help with this problem basically without access to the device. I suspect you might need to debug or add enough logging (wrap the socket etc) to prove the problem is in OkHttp before we can help.  

What are your timeouts set to?
Is it happening to any host?
just for SSL vs HTTP?
Can you reproduce with the latest released version of OkHttp?

**Comment by swankjesse** [comment]
No action to take on this.

**Comment by readersahil** [comment]
The problem is in doze mode android 7+ devices blocks internet access. I can't seem to find any way to keep okhttp socket connection alive in doze mode.

**Comment by JakeWharton** [comment]
You can't or doze mode would be ineffective. If you want to do work during
doze, use JobScheduler for it.
