### ISSUE TITLE
We can't  access the address forever after we acceessed it failed 

### ISSUE THREAD

**Issue by MrWangyaya** [square/okhttp#3548]
We need to use vpn to connect our web server. 
  If we did not use the vpn at first , it shows connected faild. That's right. But after we repeat several times, we open the vpn and connect to the web server. It also shows connected faild. We restart the App, it also doesn't working. We lost this web api forever.
  How can we fix it? Thanks!

**Comment by swankjesse** [comment]
Executable test case?

**Comment by yschimke** [comment]
Just to confirm - this is the problem you are seeing:

1. (without VPN) OkHttp connect to API - fails because no VPN
2. Start external VPN connection
3. (with VPN) OkHttp connect to API - still fails
4. Restart App
5. (with VPN) OkHttp connect to API - still fails

Based on step 5 failing, what makes you think the problem is OkHttp? Is there any evidence that other traffic is working e.g. it works with URLConnection or the Chrome browser to the same host?

**Comment by MrWangyaya** [comment]
@yschimke I'am sorry that I didn't describe clearly.☺
This is my test step:
1. with vpn OkHttp to API1 -success
2. with vpn OkHttp to API2 -success
3. without vpn OkHttp to API1 - fail
    without vpn OkHttp to API1 - fail
    without vpn OkHttp to API1 - fail
    ......
   without vpn OkHttp to API1 - fail
   ( no connect to API2)

4. with vpn OkHttp to API1 - fail
5. with vpn OkHttp to API2 -success
6. with vpn OkHttp to API1 - fail

**Comment by MrWangyaya** [comment]
@swankjesse Sorry, I need to apply the permission from my boss tomorrow. The vpn has some limit.

**Comment by yschimke** [comment]
@MrWangyaya to be clear, I don't think we want actual access to the VPN if that is what you are suggesting.  More that unless you can reproduce it in a simpler test case, or provide enough explanatory debug information to understand what is going on, then it is impossible to make a bug fix or explain what you might be doing to cause the problem.

**Comment by yschimke** [comment]
Please reopen this if you can reproduce.  n.b. If you want I can send you a dead simple Android sample app project (builds with gradle) and we can test with a public VPN.
