### ISSUE TITLE
Question: How to get case-sensitive response headers?

### ISSUE THREAD

**Issue by sammefford** [square/okhttp#3605]
It appears response.headers() returns a Headers object which only provides lower-case names for headers.  How can I access the original case of the response headers?

**Comment by EricEdens** [comment]
HTTP header names should be treated as case insensitive.

   Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace



https://tools.ietf.org/html/rfc7230#section-3.2

What's the motivation to get the original casing?


On Sep 13, 2017 10:55 AM, "Sam Mefford" <notifications@github.com> wrote:

It appears response.headers() returns a Headers object which only provides
lower-case names for headers. How can I access the original case of the
response headers?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/square/okhttp/issues/3605>, or mute the thread

**Comment by sammefford** [comment]
I would like to provide the headers to external callers of my library.  If they're looking for a header their REST API generated, and they expect to get it in the case they generated it, I'd like a way to offer that to them.  As it is, OkHttp is preventing me from doing that.

**Comment by sammefford** [comment]
To be clear, I'm not exposing OkHttp to my callers, it's internal to my library.  I'll provide them a Map<String,List<String>> of headers and values.  So they won't have the convenient case-insensitive methods of okhttp3.Headers available to them.

**Comment by swankjesse** [comment]
You probably want this: `new TreeMap(String.CASE_INSENSITIVE_ORDER)`

Note that with HTTP/2 all headers must be lowercase, so preserving case is not viable in the long term anyway.

**Comment by yschimke** [comment]
```
      System.out.println(response.headers().names());
[Accept-Ranges, Access-Control-Allow-Origin, Cache-Control,

      System.out.println(response.headers().toMultimap());
{accept-ranges=[bytes], access-control-allow-origin=[*], cache-control=[max-age=300]
```
