### ISSUE TITLE
about https

### ISSUE THREAD

**Issue by wangguifa** [square/okhttp#3606]
excuse me.Can you help me see a question? I put the https certificate on the assets package. When the certificate expires，I would like to ignore the verification certificate.So i do this：
```
private void overLockCard() {
        final TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            @Override
            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {

            }

            @Override
            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {

            }

            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
            }
        }};
        try {
            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, trustAllCerts, new SecureRandom());
            HostnameVerifier hostnameVerifier = new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            };
            OkHttpClient.Builder builder = mOkHttpClient.newBuilder();
            builder.sslSocketFactory(sslContext.getSocketFactory());
            builder.hostnameVerifier(hostnameVerifier);
            builder.build();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

But when I put the phone system time to change the time after the expiration of the certificate，The network request will appear as follows：
.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Fri Feb 09 09:54:32 GMT+08:00 2018 (compared to Sat Sep 14 15:13:55 GMT+08:00 2019)
what should I do? Thank you very much.

**Comment by yschimke** [comment]
I don't think testing via changing the phone date works, since your server should be still sending back the (theoretically) expired certificate.  Once this happens the TLS handshake fails before the TrustManager and HostnameVerifier get involved.

If this is for a production app, then you should set up your certificates such that they can rotate even every 3 months without having to expire your certificates on the client.

This is a better question for stackoverflow as it is more usage of the library than a bug report.
