### ISSUE TITLE
How to change timeout for a single request in okhttp

### ISSUE THREAD

**Issue by Ashok-Varma** [square/okhttp#3677]
What kind of issue is this? - Question. 

I asked in StackOverflow no one responded. So repeating same here :
https://stackoverflow.com/questions/46845206/how-to-change-timeout-for-a-request-in-okhttp

In general we set timeout for the okHttp client and we use single instance of that client. So, we can't change the timeout for that client once it's generated.

How to change the timeout for a particular request ?? Is there anyway to do it without creating new client??

It's very common that some calls take more time atleast 1/2 per app, which needs more timeout than others. it would be great if request object can override the default timeout.

**Comment by JakeWharton** [comment]
See https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PerCallSettings.java which creates shallow clones that only modify some settings.

**Comment by bric3** [comment]
FYI [since 3.9, it's possible to modify timeouts of in-flight calls](https://github.com/square/okhttp/blob/okhttp_3.9.x/CHANGELOG.md#:~:text=Interceptors%20are%20more%20capable.%20The%20Chain%20interface%20now%20offers%20access%20to%20the%20call%20and%20can%20adjust%20all%20call%20timeouts.%20Note%20that%20this%20change%20is%20source%2Dincompatible%20for%20code%20that%20implements%20the%20Chain%20interface.%20We%20don%27t%20expect%20this%20to%20be%20a%20problem%20in%20practice!):

https://github.com/square/okhttp/blob/36bd68aa3e93affb12504cd40454e64c6812019c/okhttp-tests/src/test/java/okhttp3/InterceptorTest.java#L747-L757
