### ISSUE TITLE
I add a header, it does not work?

### ISSUE THREAD

**Issue by axzhcode** [square/okhttp#3698]
There is a website need a Content-Type header contains"; charset=UTF-8", if not, it response wrong msg.
But When i user this:
`builder.addHeader.put("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");`
it does not work.
The FormBody used the Content-Type:
`private static final MediaType CONTENT_TYPE = MediaType.parse("application/x-www-form-urlencoded");`
and in 
`BridgeInterceptor.intercept: `
`if (contentType != null) {
        requestBuilder.header("Content-Type", contentType.toString());
}` 
this will override the header which i added.

**Comment by yschimke** [comment]
Please post on stackoverflow, and I suggest including actual running sample code.

I suggest sending your request to a service like https://requestb.in/1n2lqzb1?inspect, so that anyone can run it and that site shows the output.

Alternatively make a PR including a failing test using MockWebServer and we can fix any bugs you find.

**Comment by su1216** [comment]
you can set MediaType with body:
`RequestBody.create(type, jsonObject.toJSONString())`

**Comment by axzhcode** [comment]
@su1216 
I know this.

**Comment by axzhcode** [comment]
@yschimke 
I means, if i added a Content-Type header and used FormBody to build the request, the BridgeInterceptor would override the header which i added.
