### ISSUE TITLE
when i send some no-response requests, maybe 5 times, i can't send request any more. why? 

### ISSUE THREAD

**Issue by JunWeiAndroid** [square/okhttp#3739]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
Please provide a reproducible test or example code.  Essentially if you are reporting here it should be a bug.

If by no response you mean request that do not complete, it is probably the connection (concurrency) limits in the client that you can raise.  But it isn't clear from this report.

Try using https://httpbin.org/delay/300 (if I understood correctly) to make a reproduction, and I suggest posting to stackoverflow instead of reporting here.
