### ISSUE TITLE
bug about UnKnownHostException 

### ISSUE THREAD

**Issue by shuwenyouxi** [square/okhttp#3797]
version: 3.8.1
a mobile connect a no internet wifi(another mobile share wifi and close internet)
then call a internet request (get or post request whatevet)
I can get UnKnownHostException within 1s in some devices(like HUAWEI),
but get UnKnownHostException at 20s in some other devices(like OPPO and VIVO),
How can I get response in a short time.

**Comment by shuwenyouxi** [comment]
this is my config
`builder.connectTimeout(10, TimeUnit.SECONDS);
builder.readTimeout(10, TimeUnit.SECONDS);
builder.writeTimeout(10, TimeUnit.SECONDS);`

**Comment by yschimke** [comment]
You might have to debug on these specific devices, specifically looking at OkHttp events and Android network events. 

This is how you can capture OkHttp events, i.e. why the timeout you see is 2x the read timeout, potentially due to two different network paths tried. https://github.com/square/okhttp/wiki/Events

An Android ConnectivityManager.NetworkCallback might give you some hints about why you see different behaviour on different phones. e.g. https://github.com/yschimke/okhttp-testapp/blob/master/app/src/main/kotlin/com/squareup/okhttptestapp/network/NetworkListener.kt

Generally unless you can reproduce in a test app against a server we can access, it will be hard to investigate.  You can try with this sample app https://github.com/yschimke/okhttp-testapp. Or ask on stackoverflow.

**Comment by g19980115** [comment]
I had the same problem.

**Comment by g19980115** [comment]
Hey,you can try this,its works for me.
