### ISSUE TITLE
[Feature Request] allow supplying a different cache key derivation function for urls

### ISSUE THREAD

**Issue by 2fchar** [square/okhttp#3831]
i can understand why `okhttp3.Cache` is made final as mentioned in https://github.com/square/okhttp/issues/2740 , also mentioned in https://github.com/square/okhttp/issues/1459 , https://github.com/square/okhttp/issues/2261 , but i think a small change can be made to greatly increase flexibility, without changing it's `final` status

that is, allow providing a different `key` implementation, currently it's just a one-liner that converts a url to a string: https://github.com/square/okhttp/blob/fb284d35083e466c435565b9a1ee4092e322cc83/okhttp/src/main/java/okhttp3/Cache.java#L186
i believe adding a option to change it is easy, possibly using the builder pattern, and won't require change to any other components

**Comment by swankjesse** [comment]
Neat idea!

But one of the fundamental design decisions in our cache is to provide similar semantics to the caches in web browsers. Anything we do here would work with OkHttp but won’t work browsers. In order to get great caching everywhere – browsers, OkHttp, caching proxies, etc. – I think the best solution is to do URL canonicalization before making the HTTP request.

That said, that’s not necessarily a solution you can put to work today. For that? Maybe do some caching at the application layer before you call into OkHttp? Sorry I don’t have anything more satisfying.

**Comment by swankjesse** [comment]
Also, we can’t ever return resources retrieved over HTTP to requests made over HTTPS. That’d allow an attacker to poison the HTTPS response, which we don’t want.

**Comment by neevek** [comment]
I really need this for the scenario I am facing.

I issued a GET request with a distinct id, say a userId, along with other parameters like request signature for the server to check if the request is a valid one, the signature will change each time I make a request (timestamp may be used), now the server wants the client to cache the response for a period of time, but the client will not be able to generate the same key again, the cache will **never** be used in this case.

I can hack around the `Cache` class and make it fit my needs, but that would be annoying and more work for me to adopt official bug fixes.

I think a `CacheKeyCreator` can make the whole thing more flexible, and not violate any design principles, as long as the user (the developer) knows what (s)he is doing. For most users, they don't even need to care about this, but if someday someone needs it, it is there.

**Comment by swankjesse** [comment]
That is strange, how does it work with browsers where caches aren't comfortable?

The URL is a really awesome cache key, and URLs should be designed with caching in mind. You should use path & query for data that impacts caching (userId), and headers for things that don't (signature).

If your server developers didn't do this, they should! It'll improve caching on every HTTP client.

**Comment by neevek** [comment]
Good advice, thank you. I didn't think of storing signature in headers, which is much easier than hacking around interceptors and request parameters.

**Comment by joshfriend** [comment]
> That is strange, how does it work with browsers where caches aren't configurable?

Sometimes it doesn't work because the api was poorly designed. I had to use an API where the access token was required to be a URL query parameter. The tokens expired frequently and some of the APIs returned images.

> If your server developers didn't do this, they should! It'll improve caching on every HTTP client.

Yeah that would be nice, but it's not always possible. I'd love the flexibility to fix poor design choices in the server design at the client level.

**Comment by swankjesse** [comment]
Easiest way to do this is to promote cache-breaking stuff into the URL in a network interceptor. The initial request URL works like a cache key, and when there's a cache miss the server sees all it needs.

**Comment by yschimke** [comment]
Won't fix.
