### ISSUE TITLE
Tag information via recorded request in mockwebserver

### ISSUE THREAD

**Issue by orhanobut** [square/okhttp#3883]
I'm trying to assert the tag which is used for the request itself, unfortunately I couldn't find a way to get this information through recorded request. I did some search if there is any existing solution, but couldn't find any unfortunately. That'd be great to have this option via recorded request in MockWebServer. 

Something like below:

```
RecordedRequest recordedRequest = server.takeRequest();
assertEquals("tag", recordedRequest.getTag());
```

**Comment by artem-zinnatullin** [comment]
`Request.tag` is an `Object` which you can use if you have reference to a `Request` object. `Request.tag` doesn't participate in the data exchange during actual network request.

When you make a request to MockWebServer you're doing real HTTP request over socket, so there is no way for MockWebServer to directly get `Request.tag` because OkHttp doesn't send it.

You can have some lossy algorithm to match request received by MockWebServer or any other server  to a tag by looking at request parameters/method/etc, but it doesn't sound very reliable and useful.

However if you really need to match requests for some reason, you can add artificial header or parameter with a unique hash code or something similar that is actually sent with request so you could match them later.

**Comment by orhanobut** [comment]
I see the point, thanks. I just used a work around to intercept the request in OkHttp. Changing the header would be overkill I think, just for testing. I'm closing the issue since it's not feasible. 👍
