### ISSUE TITLE
HTTP/2 Server Push (again...)

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4156]
Would we consider supporting HTTP/2 server push now?

Adoption is still minuscule, and wins are not clear. https://blog.apnic.net/2018/04/26/adoption-performance-and-human-perception-of-http-2-server-push/

Mainly curious as it comes up related to DNS over HTTPS.  Could be a nice optimisation there.  But that is still 50/50 anyway.  So just asking the question for now.

Previous
https://github.com/square/okhttp/issues/3106
https://github.com/square/okhttp/issues/856
https://github.com/square/okhttp/issues/607

**Comment by swankjesse** [comment]
I wanna do it with fancy joining & canceling. It's difficult cause it requires some rework of our cache persistence.

**Comment by Harti** [comment]
@swankjesse In no way shall this be taken as offense - but have you considered working on this in the meantime? Closing feature requests to refer them here, where the last activity was in 2018, is somewhat awkward.

I suppose many devs will eventually move to Java 11's native HttpClient ([supporting Server Push natively](https://dzone.com/articles/http2-server-push-via-http-client-api)) which would be a shame, with OkHttp having reached its state-of-the-art-library status.
Indeed, while you may consider Server Push a nice-to-have feature, the nonexistence of the feature is a showstopper for servers with billions of daily client requests.

**Comment by yschimke** [comment]
@swankjesse is it awkward because of a non user controlled request? i.e. we'd need some hook to allow clients to cancel when it gets triggered?

Or matching against the cache.

@Harti do you have specific examples you want to support from API or Web servers? I'd love to understand the typical usage.

**Comment by Harti** [comment]
General use cases encompass (but are not limited to): 
* Batch requests resulting in multiple responses 
** Significant: Eliminates round-trip and connection pool overheads of having to make N separate requests (the Headers can sum up and get very data hungry quickly); furthermore connectivity issues are alleviated more easily (N small downloads vs. one big download)
** Neat: No longer required to define proprietary API error/success codes for each returned item; less workers required on webserver side
** Nice-to-have (better UX): The data trickles in at the client side, as opposed to having to wait for the whole batch to be processed and downloaded.
* Requests that may serve a result instantly (200/204/304), or at a later time (202)
** In HTTP/1.1 you'd manually evaluate the 202 Retry-After headers and schedule a request.
** In HTTP/2, with server push, the connection could be kept open and the processed result could be pushed.
* Requests which the server thinks should receive additional data/files for
** For instance, when you request index.html, and the server already knows that you will also need style.css, hero-banner.png and app.js, and pushes these resources along. (Many websites already do this, and our browsers deal with it automagically.)


Alas, I cannot currently offer a working example of a server-push endpoint for development and evaluation. Should that be a precondition I shall try to assist with finding a working example.

**Comment by yschimke** [comment]
I'm familiar with the concept. More interested how prevalent this is for usecases that OkHttp would generally also be used for. A real world use as an example to test against.

**Comment by Harti** [comment]
It's probably not _prevalent_, but for any application wanting to display any list of data where an item consists of both textual information and (an) image(s), it would serve most useful for the reasons explained above.

(Maybe I'm missing the actual question, I'm sorry)

**Comment by yschimke** [comment]
Yes. First, what your usage is. Second, not how useful it can be for one specific private API. More how adoption is overall in the wild.

**Comment by Harti** [comment]
I do not have objective measures for an expected adoption rate and it's not something I can argue for beyond this opinion. 
Developers would need to adjust to this on both client and backend side, which is something that will only happen over the years. Quite unlikely that many would, as the paradigm is fairly complex and unexplored (or they have been using Websockets instead). The benefit over regular HTTP/2 (or HTTP/1.1) overhead isn't really relevant to most low-/medium-scale applications. 

I don't mean to sound entitled to this feature at all - just wanted to friendly ping you since it's something you've seemingly been wanting to do, and it's probably _the_ most talked about feature when researching how to implement HTTP/2 with Java. 
If it doesn't bother you that developers requiring such functionality might eventually move away from OkHttp and instead use Java's HttpClient (especially once Android supports JDK 11), then I agree that the general library benefit isn't big enough to warrant the implementation effort. In that case I suggest this ticket be closed as "won't do".


I must not disclose my exact usage scenario, but for what it's worth, here is the general idea:

From an OAuth-protected API, JSON data (text/json) and unknown related data of incompatible content types (e.g. image/webp) are fetched. For one, some data may not be there yet and are generated on-demand. The most crucial point however is to keep the total data usage footprint low by avoiding unnecessary outbound requests (and avoiding unnecessary inbound transfer of image URLs and the proprietary evaluation of those which makes the code extremely messy).

Instead of 100 subsequent requests (with 100 responses), 1 request should be made (with the same 100 responses, except asynchronously received, handled either with regular Callbacks or Observables/Promises) - effectively reducing traffic incurred by HTTP Headers by up to 50% (though HPACK will mitigate some of this).

**Comment by swankjesse** [comment]
I think we should abandon server push and instead support early hints. It's a better design that avoids a lot of the drawbacks of server push.
https://tools.ietf.org/html/rfc8297

**Comment by yschimke** [comment]
Push client support looks decent

https://dev.to/meyer9/http-2-server-push-explained-4gh

![image](https://user-images.githubusercontent.com/231923/79422315-904c9400-7fb4-11ea-82fb-d016c8a5c677.png)

But I've only really found test servers using it.  Nothing compelling to say implementing it would help more than a few specific users.  So I agree, and I'll close this issue unless we decide to support.

```
$ okurl --frames https://http2-push.appspot.com/
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>> 0x00000000     6 SETTINGS
>> 0x00000000     4 WINDOW_UPDATE
<< 0x00000000    18 SETTINGS
<< 0x00000000     4 WINDOW_UPDATE
>> 0x00000000     0 SETTINGS      ACK
<< 0x00000000     0 SETTINGS      ACK
>> 0x00000003    38 HEADERS       END_STREAM|END_HEADERS
<< 0x00000003   164 PUSH_PROMISE  END_PUSH_PROMISE
<< 0x00000003    27 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000002     4 RST_STREAM
<< 0x00000003    28 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000004     4 RST_STREAM
<< 0x00000003    53 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000006     4 RST_STREAM
>> 0x00000008     4 RST_STREAM
<< 0x00000003    49 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x0000000a     4 RST_STREAM
<< 0x00000003    50 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x0000000c     4 RST_STREAM
<< 0x00000003    54 PUSH_PROMISE  END_PUSH_PROMISE
<< 0x00000003    26 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x0000000e     4 RST_STREAM
>> 0x00000010     4 RST_STREAM
<< 0x00000003    35 PUSH_PROMISE  END_PUSH_PROMISE
<< 0x00000003    60 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000012     4 RST_STREAM
<< 0x00000003    46 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000014     4 RST_STREAM
<< 0x00000003    59 PUSH_PROMISE  END_PUSH_PROMISE
>> 0x00000016     4 RST_STREAM
<< 0x00000003  1115 HEADERS       END_HEADERS
>> 0x00000018     4 RST_STREAM
<< 0x00000003  2262 DATA
<< 0x00000003  1339 DATA
<< 0x00000003     0 DATA          END_STREAM
```

**Comment by yschimke** [comment]
FWIW an interesting post on the implementation challenges for push https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

**Comment by Dave645** [comment]
I think **HTTP/2 Server Push** is very useful and should be implemented.

Apple's original **Low-Latency HTTP Live Streaming (HLS)** specification had **HTTP/2 Server Push** as a requirement.

**HLS** is the most used way of live streaming in the world, and **LHLS** lowers latency to a second or two from real-time.

In **LHLS** the client ends up requesting two files multiple times a second _(because part segments are video clips of half a second or less each)_. The first file it requests is the m3u8 playlist file and then it reads the file and immediately requests the video clip it's been awaiting for, it cannot request the video clip beforehand because it does not no the corresponding URL to call. But with **HTTP/2 Server Push** the server obviously knows what clip the client will be requesting after it reads the m3u8 playlist file, so to reduce 50% load on the server it immediately sends the clip with the m3u8 playlist file every time to avoid the client requesting the clip milliseconds afterward.

Source WWDC2019 Live Event:
https://developer.apple.com/videos/play/wwdc2019/502/

**Comment by yschimke** [comment]
Sounds conpelling.

Is it currently implemented as in any public servers to test? What about clients? Will clients like exoplayer expect it and make the right requests, if so does it work with cronet or other http clients to compare against?

**Comment by funky-eyes** [comment]
Hi @yschimke — I’d like to know whether this capability is already supported.

In many traditional configuration or registry centers, clients are notified of updates via long polling (or similar mechanisms), and then the client pulls the updated config or registry list. Under HTTP/1.x, that pattern can cause the server’s bandwidth to spike and produces multiple events/round trips (notification + client fetch). By contrast, using HTTP/2 server push the server can batch-push the latest configuration or service lists to clients and send only incremental (delta) changes. That approach is far more reliable and efficient and uses significantly fewer server resources than HTTP/1.x + long polling. For these reasons I believe this feature is necessary.

**Comment by yschimke** [comment]
No public API for Push.

It would have to be configured here https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt#L161

```
  private fun startHttp2() {
    javaNetSocket.soTimeout = 0 // HTTP/2 connection timeouts are set per-stream.
    val flowControlListener = connectionListener as? FlowControlListener ?: FlowControlListener.None
    val http2Connection =
      Http2Connection
        .Builder(client = true, taskRunner)
        .socket(socket, route.address.url.host)
        .listener(this)
        .pingIntervalMillis(pingIntervalMillis)
        .flowControlListener(flowControlListener)
        .pushObserver(object : PushObserver { // does not exist
          override fun onRequest(streamId: Int, requestHeaders: List<Header>): Boolean = TODO("Not yet implemented")

          override fun onHeaders(streamId: Int, responseHeaders: List<Header>, last: Boolean): Boolean = TODO("Not yet implemented")

          override fun onData(streamId: Int, source: BufferedSource, byteCount: Int, last: Boolean): Boolean = TODO("Not yet implemented")

          override fun onReset(streamId: Int, errorCode: ErrorCode): Unit = TODO("Not yet implemented")
        }) 
        .build()
```

But currently defaults to CANCEL

https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/PushObserver.kt#L90

**Comment by yschimke** [comment]
> For these reasons I believe this feature is necessary.

@funky-eyes I think what would help here is existing precedence of this in public APIs or clients. It might be true that you would find it great to use, and can use it in other platforms, but the bar is more around evidence that it's a supported and adopted feature across servers and user agents.

Basically is OkHttp missing a common feature that degrades functionality for clients that they are expected to be able to support?

**Comment by funky-eyes** [comment]
> > For these reasons I believe this feature is necessary.
> 
> [@funky-eyes](https://github.com/funky-eyes) I think what would help here is existing precedence of this in public APIs or clients. It might be true that you would find it great to use, and can use it in other platforms, but the bar is more around evidence that it's a supported and adopted feature across servers and user agents.
> 
> Basically is OkHttp missing a common feature that degrades functionality for clients that they are expected to be able to support?

In the industry, frameworks like Dubbo and Netty have already added support for HTTP/2 and HTTP/3, including unidirectional and bidirectional streaming, and these features have gained significant adoption within their respective communities. However, Dubbo comes with a high usage cost for clients—it feels overly heavyweight. Netty, on the other hand, lacks simplicity and convenience, requiring developers to build their own wrappers. Meanwhile, gRPC, built on HTTP/2, has driven widespread adoption of unidirectional and bidirectional streaming among a large user base. I believe this clearly represents an emerging trend, which is why I consider support for server-side push to be highly necessary.

**Comment by yschimke** [comment]
I wasn't aware that gRPC was using HTTP/2 server pushes.  My understanding is that it just maps to the low level HTTP/2 streams and (ideally efficiently) frames. https://grpc.github.io/grpc/core/md_doc__p_r_o_t_o_c_o_l-_h_t_t_p2.html

OkHttp already supports duplex requests - https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/RequestBody.kt#L49

But if you want to control every frame, then you probably want to be using Netty for it. OkHttp hides those implementation details.

**Comment by funky-eyes** [comment]
> I wasn't aware that gRPC was using HTTP/2 server pushes. My understanding is that it just maps to the low level HTTP/2 streams and (ideally efficiently) frames. https://grpc.github.io/grpc/core/md_doc__p_r_o_t_o_c_o_l-_h_t_t_p2.html
> 
> OkHttp already supports duplex requests -
> 
> [okhttp/okhttp/src/commonJvmAndroid/kotlin/okhttp3/RequestBody.kt](https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/RequestBody.kt#L49)
> 
> Line 49 in [8e0cc1b](/square/okhttp/commit/8e0cc1b398a10c27a0921a14bc53ca770169d83c)
> 
>     * A duplex request body is special in how it is **transmitted** on the network and 
> But if you want to control every frame, then you probably want to be using Netty for it. OkHttp hides those implementation details.

I apologize — I mistakenly confused Streaming Response with Server Push. While Streaming Response can mimic some of Server Push’s behavior, Server Push is clearly better suited for a configuration registry, although it may be more complex to implement.

**Comment by yschimke** [comment]
Can you point at active use and adoption of server push?

I think I'm mostly aware of Apple APNS.

**Comment by swankjesse** [comment]
Relevant:
https://developer.chrome.com/blog/removing-push

**Comment by YvCeung** [comment]
> No public API for Push.
> 
> It would have to be configured here
> 
> [okhttp/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt](https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/connection/RealConnection.kt#L161)
> 
> Line 161 in [8e0cc1b](/square/okhttp/commit/8e0cc1b398a10c27a0921a14bc53ca770169d83c)
> 
>  private fun startHttp2() { 
> ```
>   private fun startHttp2() {
>     javaNetSocket.soTimeout = 0 // HTTP/2 connection timeouts are set per-stream.
>     val flowControlListener = connectionListener as? FlowControlListener ?: FlowControlListener.None
>     val http2Connection =
>       Http2Connection
>         .Builder(client = true, taskRunner)
>         .socket(socket, route.address.url.host)
>         .listener(this)
>         .pingIntervalMillis(pingIntervalMillis)
>         .flowControlListener(flowControlListener)
>         .pushObserver(object : PushObserver { // does not exist
>           override fun onRequest(streamId: Int, requestHeaders: List<Header>): Boolean = TODO("Not yet implemented")
> 
>           override fun onHeaders(streamId: Int, responseHeaders: List<Header>, last: Boolean): Boolean = TODO("Not yet implemented")
> 
>           override fun onData(streamId: Int, source: BufferedSource, byteCount: Int, last: Boolean): Boolean = TODO("Not yet implemented")
> 
>           override fun onReset(streamId: Int, errorCode: ErrorCode): Unit = TODO("Not yet implemented")
>         }) 
>         .build()
> ```
> 
> But currently defaults to CANCEL
> 
> [okhttp/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/PushObserver.kt](https://github.com/square/okhttp/blob/8e0cc1b398a10c27a0921a14bc53ca770169d83c/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/http2/PushObserver.kt#L90)
> 
> Line 90 in [8e0cc1b](/square/okhttp/commit/8e0cc1b398a10c27a0921a14bc53ca770169d83c)
> 
>  @JvmField val CANCEL: PushObserver = PushObserverCancel()

@yschimke I would like to know if OkHttp currently provides an API that supports processing each HTTP/2 data frame as it arrives, allowing custom logic to be executed immediately upon receiving each frame, rather than waiting for the complete response body to be assembled.

My use case is: after establishing an HTTP/2 connection with the server, the server sends data frames periodically (e.g., every 2 seconds) when events occur. I need to process each data frame in real-time as it arrives, rather than reading from a buffered response body.

From my understanding, `response.body().source()` reads from OkHttp's internal buffer after frames have been assembled, not directly from the network as each frame arrives. Is there a lower-level API or mechanism in OkHttp that allows frame-by-frame processing?

**Comment by yschimke** [comment]
No, not a public one. 

It's been discussed before, but is not something that fits OkHttp public API
