### ISSUE TITLE
[Feature Request] Support "h2c"

### ISSUE THREAD

**Issue by moonfruit** [square/okhttp#4951]
I know that **okhttp** now have already supported `h2-prior-knowledge`.

However, it is still inconvenient to use, because `h2_prior_knowledge` cannot be used with other protocols at the same time.

In my project, I use **okhttp** to access the REST APIs of other modules inside the project. Because the project will eventually be deployed on the intranet, there is no incentive to use https. At the same time, I need to use **okhttp** to access some external resources on the Internet. At this time, I have to instantiate two `OkHttpClient`s. It is very inconvenient to always pay attention to which one to access which resource.

If **okhttp** supports `h2c`, it will be very convenient to be compatible with both `h2` and `http/1.1` servers.
And it also matches the spirit of **okhttp** that recommending only one `OkHttpClient`.

**Comment by yschimke** [comment]
This seems like a reasonable request, but may not be a sufficient concern to get added in.  I'll let others weigh in on that.

One thing I'm curious about though is whether you consider these internal services to be production?  I can understand HTTP for development reasons, but I would expect even internally that most deployed software would use internal CAs etc and run traffic over secure connections?  To protect user tokens, content, passwords and also for benefit of things like HTTP/2.  HTTP/2 doesn't work generally over plaintext, e.g. in browsers and I believe a big part of that design is the expectation of HTTPS as a baseline since it's usually available internally even for small intranet sites at small companies.

**Comment by moonfruit** [comment]
Because `http/2` support binary data format, persistent tcp connections, multiplexing, and header compression and reuse, `http/2` will have a lower latency than `http/1.1` and a higher throughput rate.
So it will be the best companion for RPC. And for internal RPC, `h2c` is easier to deploy than `h2` and has less stress on the hardware.
For example, **gRPC** supports both `h2` and `h2c`.

**Comment by swankjesse** [comment]
How do you specificy which calls use h2c?

**Comment by moonfruit** [comment]
Maybe, `h2c` is not enabled by default. But if I add `h2c` to the `OkHttpClient`, every **http** call add `Upgrade` to the http header. If the server support it, it will go with `h2c`. If the server does not support it, it simply ignore it, and it will go with 'http/1.1'.

**Comment by swankjesse** [comment]
I don’t plan to take any action here. Creating separate HTTP clients for h2c vs. not is best.

**Comment by moonfruit** [comment]
It's sadly to hear that.

**Comment by 0x6666** [comment]
It's sadly to hear that.

**Comment by fuzigege** [comment]
It's sadly to hear that.
