### ISSUE TITLE
Flaky test: okhttp3.internal.ws.WebSocketHttpTest + RealWebSocketTest

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4953]
https://circleci.com/gh/square/okhttp/1293

```
okhttp3.internal.ws.WebSocketHttpTest > wssScheme FAILED
    java.lang.AssertionError: Expected Open but was Failure[java.net.SocketTimeoutException: Read timed out]
        at okhttp3.internal.ws.WebSocketRecorder.assertOpen(WebSocketRecorder.java:169)
        at okhttp3.internal.ws.WebSocketHttpTest.websocketScheme(WebSocketHttpTest.java:780)
        at okhttp3.internal.ws.WebSocketHttpTest.wssScheme(WebSocketHttpTest.java:501)
```

**Comment by galderz** [comment]
It's hard to say whether there's a bug there with the info available, but my suspicion would be that this is the result of the CI machine being slow at this particular stage, beyond 500ms of the read timeout that the test is configured with. This could potentially happen in constrained/shared envs such as online CI setups.

Although you could just increase the default read timeout of the test, it'd make tests relying on those timeouts slower to fail, which could be detrimental in day to day development.

One day to avoid this issue is to centralise all test timeouts, and have a way to say that when running in CI, you'd want those timeouts to be N times the default test timeouts. E.g. read timeout normally is 500ms but on CI say 10 * 500ms. This would enable you to keep snappy testsuite while having more forgiving timeouts for shared/constrained envs.

I can explore this avenue if it's of interest to the maintainers.

**Comment by galderz** [comment]
I'm not sure it's possible here, since I'm not sure if the read timeout is triggered by the okhttp itself or the JDK (?), but if the timeout is triggered by okhttp, you could wrap time around a time service and move time programmatically within the tests. That way you'd get predictable timeouts. I've used this method in projects where we wanted to test time based eviction. However, if the time out can come from JDK or JVM code, you don't have such control and my previous suggestion would be preferable then.

**Comment by galderz** [comment]
I have double checked and in this particular case the socket timeout exception would come from Java's Socket API, so to protect this I'd go with my first suggestion.

**Comment by yschimke** [comment]
https://circleci.com/build-insights/gh/square/okhttp/master

**Comment by yschimke** [comment]
Dupe of https://github.com/square/okhttp/issues/5708
