### ISSUE TITLE
provide contributor guidelines

### ISSUE THREAD

**Issue by sjconnor** [square/okhttp#5049]
It would be good to know how the okhttp community wants new contributors to proceed, preferably as a typical CONTRIBUTING doc alongside the README. 

A decent template can be found here: https://github.com/nayafia/contributing-template

A good real-world example can be seen here: https://github.com/chef/chef/blob/master/CONTRIBUTING.md

**Comment by swankjesse** [comment]
Yep.

Many open source projects are quite welcoming to new contributors. I’m reluctant to solicit new contributors because I want this project to remain small and focused. I prefer to produce a very high-quality artifact over building a flourishing community of contributors.

That said, if you’re a potential contributor, our contributing guide is this video:
https://www.youtube.com/watch?v=PCxz2LEmuL4

**Comment by jamesralstin** [comment]
Hey Jesse, not to keep bringing up the subject, but would it be worth including what you mentioned above either in the project read me, or perhaps on the OKHttp site, or link the <a href="https://square.github.io/okhttp/#contributing">contributing</a> portion of the site in the readme?

**Comment by MonikaJethani** [comment]
@swankjesse @JakeWharton Can I work on this?

**Comment by swankjesse** [comment]
I'd like to do this myself. It's about defining our policy and it's not a good fit for contributors.

**Comment by swankjesse** [comment]
Voila: https://github.com/square/okhttp/blob/master/CONTRIBUTING.md
