### ISSUE TITLE
[4.0.0-alpha02] Call.clone is not accessible anymore

### ISSUE THREAD

**Issue by rubengees** [square/okhttp#5161]
I just tried out the latest alpha to see what would be required for the migration and found an incompatiblity! `Call.clone` is not accessible anymore, since it is `protected` now. `RealCall` simply `overrides` the method, without adjusting the visiblity to `public`.

This comes from Kotlin code. I see that OkHttp has Java tests which call `clone`, so I'm not sure why it works in Java, but not in Kotlin.

**Comment by swankjesse** [comment]
Yikes. Thanks for reporting!

**Comment by monkey-mas** [comment]
It seems like the default visibility modifier for overridden function is `public` in Java code when we don't explicitly assign a new modifier to `protected` _base_ function like our case. On the contrary, an overridden function has the same modifier as the _base_ function's when we don't specify a new one in Kotlin, which is expected.

**Comment by monkey-mas** [comment]
### Proposal
1. Override `clone()` with `public` visibility modifier.
I guess Kotlin allows us to _modify_  the visibility of overridden function.
e.g. `public override fun clone(): Call`
I can't find the spec for overridden visibility modifier in [Kotlin-spec#inheritance-delegation](https://kotlin.github.io/kotlin-spec/#inheritance-delegation) though...

2. Depricate `clone()` and define a new equivalent function.
Since the visibility of `Cloneable#close()` is defined `protected` in Kotlin, it's probably more Kotlin-ish way to maintain its default visibility.
 
@swankjesse Which one is good for us? Or neither of them is nice?

**Comment by JakeWharton** [comment]
Java also allows expanding the visibility of an overridden function.
