### ISSUE TITLE
Make HttpLoggingInterceptor log-event configurable

### ISSUE THREAD

**Issue by skylupop** [square/okhttp#5293]
HttpLoggingInterceptor traces all requests, and Level permits to configure **what** to log. It would be nice to have the possibility to decide **when** to log too, e.g. via a boolean flag (logOnlyOnFailure), an enum or a boolean supplier that takes request and response as arguments.

**Comment by yschimke** [comment]
There are a lot of requests to customise this HttpLoggingInterceptor.  But this limited feature set is by design and the advice is to copy and paste and customise to your own requirements.

A similar case can be made for the listener, but you can see even internally we copy and customise rather than building something that meets all possible requirements https://github.com/square/okhttp/blob/master/okhttp-testing-support/src/main/java/okhttp3/ClientRuleEventListener.kt
