### ISSUE TITLE
🙉Why return error message = "Client error" for http error code = 401 ?

### ISSUE THREAD

**Issue by alexei-28** [square/okhttp#5619]
In my Android project I use this test:

```
   mockServer.enqueue(
            MockResponse()
                .setResponseCode(401)
        )
```

Standard error message for code **401** is **Unauthorized** . But response message from mockServer is "Client error".
But I need standard error message.

**Comment by JakeWharton** [comment]
You can call `setStatus` to set a full status line with whatever message you would like. OkHttp uses simple mappings based on the first digit only to avoid having to maintain the full table. Messages are largely irrelevant and should never be relied upon by application code to be set to a certain value for a given status code which is why we took this approach.
