### ISSUE TITLE
Inconsistent timeout behaviour in secureConnect 

### ISSUE THREAD

**Issue by setiawanp** [square/okhttp#5812]
I'm experiencing inconsistent timeout behaviour in OkHttp 4.4.0. This is my setup:
1. I'm attaching `PrintingEventListener` to OkHttp just like you guys did in the [sample](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PrintEvents.java)
2. Set timeout:
      >connectTimeout = 12000 ms
     readTimeout = 30000 ms
     writeTimeout = 5000 ms
3. Make an API call to `https://httpstat.us/200?sleep=30000`

PS: I'm using Network Link Conditioner to simulate slow network connection here

Based on several retries, I found inconsistency how timeout works when OkHttp enters `secureConnectStart` (based on the `PrintingEventListener` that I have attached).

**Case 1 (correct behaviour):**
```
GET https://httpstat.us/200?sleep=30000
0.000 callStart
0.004 proxySelectStart
0.006 proxySelectEnd
0.006 dnsStart
0.009 dnsEnd
0.009 connectStart
11.539 secureConnectStart
41.573 connectFailed
41.574 callFailed
```
Notice that from `secureConnectStart` to `connectFailed` took around 30 secs which is expected because I set read timeout to 30000 ms

--------------------------------

**Case 2 (incorrect behaviour):**
```
GET https://httpstat.us/200?sleep=30000
0.000 callStart
0.005 proxySelectStart
0.005 proxySelectEnd
0.005 dnsStart
0.009 dnsEnd
0.009 connectStart
9.078 secureConnectStart
57.669 secureConnectEnd
57.670 connectEnd
57.671 connectionAcquired
57.672 requestHeadersStart
57.672 requestHeadersEnd
87.678 responseFailed
87.680 connectionReleased
87.681 callFailed
```
Notice that from `secureConnectStart` to `secureConnectEnd` it took around 47 secs which I wasn't expecting because OkHttp should just cut the connection when it reached 30 secs.

I was thinking to create unit tests for this, but couldn't think of anything to simulate bad network condition in unit test. So, pardon me for not having it. But let me know if you need more data to debug around this.

**Comment by swankjesse** [comment]
The read timeout is the maximum amount of time to wait between expected packets, independent of overall throughput.  Suppose we have a 30 second timeout:

If the server sends 150 bytes, sleeps 40 seconds, and then sends 150 bytes again, this will fail with a timeout.

If the server sends 100 bytes, sleeps 20 s, sends 100 bytes, sleeps 20 s, and sends 100 bytes, this will not fail with a timeout. At no point did the client wait longer than 30 seconds.

Because the TLS handshake involves multiple round trips, the total duration of the handshake can exceed the duration of the read timeout.  If you want a hard ceiling on the amount of time to wait, configure a call timeout. Or call `deadline(30, SECONDS)` on the `Timeout` object.

https://square.github.io/okio/2.x/okio/okio/-timeout/

**Comment by setiawanp** [comment]
Thanks for pointing that out. That makes everything clear.
