### ISSUE TITLE
Add WebSocket EventListener

### ISSUE THREAD

**Issue by change2** [square/okhttp#5833]
i use okhttp connect a websocket service ,  i want know websocket heart beat failed can tell my program,but now can'not 
i hope
websocket heartbeat  failed. can throw special exception ?
if failed can log heart beat failed . but now nothing

**Comment by yschimke** [comment]
Heartbeats are not directly exposed, sorry.  They are deliberately not public API.

**Comment by changealice** [comment]
can print some log may let me known heartbeat heathly ?

**Comment by yschimke** [comment]
This is currently disabled so an enhancement we should consider on it's merits.

```
  @Test public void webSocketsDontTriggerEventListener() {
    RecordingEventListener listener = new RecordingEventListener();
```

**Comment by ShivamArya2357** [comment]
I want to work in this issue

**Comment by yschimke** [comment]
> I want to work in this issue

@ShivamArya2357 A few concerns here

1) I know @swankjesse prefers to avoid "licking the cookie". If someone submits a PR, it will be reviewed, but generally we don't tell people not to work on things because someone else has already claimed it.  An inflight PR would generally show that you are actively working on it already.
2) This is a non-trivial PR, so potentially a frustrating experience for a first time contributor and the reviewer.

Those generally combine to discourage first time contributors unfortunately, but for a non-trivial PR the work reviewing iterative versions of the PR is potentially far greater than writing it.

That leaves a gap where you ignore my (friendly) advice, and submit a high quality PR that looks close enough to ready that someone on the project reviews your PR and helps get it ready to land.  That's how the vast majority of external PRs tend to succeed.  Still, there are examples where a high quality PR is still considered against other project aims (e.g. code simplicity) and doesn't land.  So this can be frustrating for you.

**Comment by swankjesse** [comment]
This issue isn’t available for new contributors.

**Comment by bentemple** [comment]
Having this listener would also be really helpful since then we can use it to determine the average latency to the server.

Ideally the listener callback would either contain the total round trip ping/pong time with the server, OR a callback whenever the ping is called, and a callback whenever the pong is received.

**Comment by baldhead69** [comment]
Hi,

Some evolution on this ????

**Comment by yschimke** [comment]
No.  I was hoping to look into it, but haven't started anything. Not sure if anyone else is looking into it.

**Comment by yschimke** [comment]
Closing as low priority.
