### ISSUE TITLE
Split up longest running tests

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5911]
CallTest and HttpOverHttp2Test are outliers taking much longer than all other tests.  I want to float the idea of splitting these into CallXTest, CallYTest.  We can find interesting splits of tests that make sense.

CI and local ./gradlew test will run faster.

**Comment by swankjesse** [comment]
I don't love organizing JUnit tests because most of our tests are exercising how pairs of features interact. Having a RedirectTest and a CacheTest means we don't have an obvious test for redirectCached().

With that rant out of the way, I don't actually need our test classes to mean anything; they're just carriers of test methods.

**Comment by yschimke** [comment]
I'm coming about this purely pragmatically, I want tests to run faster, so I'm waiting less.

```
$ ./gradlew test --scan
```

https://scans.gradle.com/s/6ky7ew3nigmuq

I'm going to close for now.  Use CI to run tests as much as possible anyway.
