### ISSUE TITLE
connectTimeout more than 30 seconds does not work for okhttp

### ISSUE THREAD

**Issue by piyushspss** [square/okhttp#5912]
I am trying to set connectTimeout to 2 minutes, but still the tries fails after 30 seconds only.

My client looks like this:

client = new OkHttpClient.Builder()
            .callTimeout(2, TimeUnit.MINUTES)
            .connectTimeout(2, TimeUnit.MINUTES)
            .writeTimeout(2, TimeUnit.MINUTES)
            .readTimeout(2, TimeUnit.MINUTES)
            .build();

public Call callReq(Callback callback) {

    Request.Builder builder = new Request.Builder()
            .url("http://203.0.113.1");

    //Create request builder
    final Request request = builder
            .build();

    Call call = client.newCall(request);

    call.enqueue(callback);
    return call;
}
The failure response of this call I am receiving in 30 seconds. I wanted that to wait for 2 minutes. It works if I reduce the timeout to 15 seconds.

**Comment by yschimke** [comment]
I can't reproduce, answered on https://stackoverflow.com/questions/60874223/connecttimeout-more-than-30-seconds-does-not-work-for-okhttp/60913612#60913612

**Comment by chriswoodle** [comment]
I have the same issue, com.squareup.okhttp3:okhttp:3.12.0. My requests seem to exit after 30 sec, but no exception is thrown.

**Comment by yschimke** [comment]
@chriswoodle If you can provide a reproducible test case we can investigate, otherwise I suggest discussing on the stackoverflow question.

**Comment by chriswoodle** [comment]
@yschimke I can put something together, It's somewhat involved though, Nodejs, ngrok and an android app.

**Comment by chriswoodle** [comment]
@yschimke I put something together, It's somewhat involved though, Nodejs, ngrok and an android app. https://github.com/chriswoodle/okhttp-issue Using com.squareup.okhttp3:okhttp:3.12.0, since this app must target api lvel 17.

It is an android app and a nodejs express server. I've tested the server using postman to confirm that it is not timing out requests.
![image](https://user-images.githubusercontent.com/11614325/104068330-b6fdcb00-51d2-11eb-90e5-77e1d1124790.png)

I''ve tested setting the okhttpclient timeout to 15 sec, and that correctly throws an exception. Hhowever, with the timeout set to anything more than 30 sec. 30 sec after making a request the following comes back.
```
 <HTML>
    <HEAD>
    <TITLE>Inactivity Timeout</TITLE>
    </HEAD>
    
    <BODY BGCOLOR="white" FGCOLOR="black">
    <H1>Inactivity Timeout</H1>
    <HR>
    
    <FONT FACE="Helvetica,Arial"><B>
    Description: Too much time has passed without sending any data for document. 
    </B></FONT>
    <HR>
    </BODY>
```

Here are some android logs if they are helpful. 
![image](https://user-images.githubusercontent.com/11614325/104068533-1a87f880-51d3-11eb-9c43-c2b0a42ffc15.png)

Let me know if I can do anything to help or test. Thanks.

**Comment by yschimke** [comment]
If your server is returning this error then there I not much OkHttp can do.

**Comment by chriswoodle** [comment]
That response is not from the server. It is however returned by the okhttpclient call. Maybe there is some other network issue with my hardware, I just tested in an emulator and there is no issue.

**Comment by chriswoodle** [comment]
Actually It looks like this was a network proxy issue and my request was being timed out by something else. Thank you for your help.
