### ISSUE TITLE
Fancy Joining and Canceling

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#607]
Features:
- Don't call the application until _N_ bytes are ready
- Buffer on disk before we call the application!
- Join multiple requests
- Cancel response receivers

**Comment by Sheikh-Aman** [comment]
> I think this will be the headline feature for our 3.0 release.
> 
> In today's OkHttp:
> 
>     * `http/1.1` synchronous calls do blocking writes and blocking reads
> 
>     * `spdy` and `http/2` synchronous calls do blocking writes; and read from an in-memory buffer that's bounded by window management.
> 
> 
> For 3.0, I'd like to introduce a better dispatcher that works for all protocols, using spdy-style thread management for all HTTP calls. The dispatcher would own caching, joining, and server-push. It would take over some responsibilities from HttpEngine, and hopefully cause the HttpTransport interface to shrink dramatically.
> 
> Internally, dispatcher's model is interested in tracking which requests are currently in flight, and who those requests service. It needs to use each cache entry as a coordination point between callers, so that two callers requesting the same cached resource yield only one network call, even if the 2nd call is made before the first completes.

Has this been implemented in OkHttp3?

**Comment by swankjesse** [comment]
We'll close the issue when it's done.

**Comment by vkotovv** [comment]
Any updates on this? [The comment here](https://stackoverflow.com/a/32642765/1000551) states that this was fixed.

**Comment by yschimke** [comment]
The thread changes have fed through.  Any work here is probably behind coroutines support on kotlin.

**Comment by skusuj** [comment]
Hi swankjesse,

My team is working on video experience using Exoplayer which uses OkHttpClient for network calls. We plan to prefetch content to reduce the start up latency, as per your below statement, 

_Internally, dispatcher's model is interested in tracking which requests are currently in flight, and who those requests service. It needs to use each cache entry as a coordination point between callers, so that two callers requesting the same cached resource yield only one network call, even if the 2nd call is made before the first completes._

To enable request merging do we need to enable caching on OkHttpClient or is this behavior available by default? My concern here is, since we already have caching enabled for exoplayer enabling it again on okhttpclient would mean caching data at 2 places.

**Comment by yschimke** [comment]
I'm not extremely familiar with the caching semantics of ExoPlayer or Media3 (it's successor).  

OkHttp shouldn't be caching these anyway, because it doesn't support Partial Responses.  https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cache/#cache-optimization.  Which is good because I think the cache key would ignore headers anyway.

But I'd strongly advise you to cache using ExoPlayer's logic only. Disable the cache for these requests in OkHttp, so you don't (as you say) end up caching data at 2 places.  But you should rely on ExoPlayer avoiding duplicate work.  Use it's APIs to fetch the data you need.

As you are probably aware, If rather than prefetching just part of the stream, you want to download the media for offline playback, ExoPlayer also supports that.

It's the right place to handle these concerns.

BTW I'm just reading up on Range headers and Caching, and not much clearer on what you should expect if it was implemented.  https://kevincox.ca/2021/06/04/http-range-caching/

**Comment by skusuj** [comment]
Thanks for responding yschimke@. I will surely look into ExoPlayer for combining network calls for same resource. One thing i wanted to understand is, if caching is enabled on OKHttp would it make an entry in the cache before going to fetch the content or once we fetch and read the content is when it makes the entry? Why because if OkHttp makes an entry in the cache after the content is fetched and read then we wont we able to avoid subsequent network calls for same resource before first request is complete. 

We want to fetch part of the stream because we aren't 100% sure if the user would play the video or not considering there are lot of other features on the page for user to check and user would be browsing through lot of such pages.

**Comment by yschimke** [comment]
I'm pretty sure OkHttp doesn't cache Partial responses at all.

Cc @swankjesse
