### ISSUE TITLE
Exclude sensitive information from body

### ISSUE THREAD

**Issue by raderio** [square/okhttp#6085]
We need a way to hide(replace with "****") some sensitive information from the body.

Is there something similar to `redactHeader` from `HttpLoggingInterceptor` but for the body properties?

**Comment by yschimke** [comment]
We generally don't add incremental new features to the http logging interceptor. Even if clearly useful like this.

I'd suggest you fork this module and add the features you need to a local codebase. If you feel strongly it should be in a shared utility library instead of your codebase, you could even publish it as a library on GitHub.  There are lots of individual requests that all make sense for this area, which is why we don't add them. The change rate of the public API for this would be much faster than the rest of the core of OkHttp.
