### ISSUE TITLE
IllegalStateException When Building with -repackageclasses

### ISSUE THREAD

**Issue by DSinge** [square/okhttp#6092]
OkHttp version: 4.7.2

I'm getting a crash when running my app built with the `-repackageclasses ''` proguard rule.
Traced the issue down to using `package.name` [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidLog.kt#L57)

```
Caused by: java.lang.IllegalStateException: OkHttpClient::class.java.`package` must not be null
  at sW1.<clinit>(AndroidLog.kt:3)
  at pW1.<clinit>(Platform.kt:2) 
  at WT1.<init>(OkHttpClient.kt:73) 
```

**Comment by yschimke** [comment]
Thanks for the report, I'll take a look.

**Comment by yschimke** [comment]
Not immediately clear what the fix is.

We want the current behaviour generally for JVM including when OkHttp is shaded.  We should continue to run fine but use a different prefix of loggers.

On Android, we want to shorten our log labels.  Until proguard gets involved, nothing can be null by definition.  Only types like arrays, primitives or Void should have a null package.  And no package should have a null name.

Maybe this would work?

```
  private val knownLoggers = LinkedHashMap<String, String>().apply {
    val packageName = OkHttpClient::class.java.`package`?.name

    if (packageName != null) {
      this[packageName] = "OkHttp"
    }

    this[OkHttpClient::class.java.name] = "okhttp.OkHttpClient"
    this[Http2::class.java.name] = "okhttp.Http2"
    this[TaskRunner::class.java.name] = "okhttp.TaskRunner"
  }.toMap()
```

This option isn't in our normal proguard rules https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

**Comment by yschimke** [comment]
@DSinge do you want to try building a snapshot from https://github.com/square/okhttp/pull/6094/files

And seeing whether it fixes it for you?

**Comment by DSinge** [comment]
Sure, I could give it a shot later today

**Comment by DSinge** [comment]
@yschimke That does seem to fix the problem. Thank you!
But will not having that map entry cause problems?

**Comment by yschimke** [comment]
@DSinge Thanks, should be fixed in the next release https://github.com/square/okhttp/pull/6094

**Comment by yschimke** [comment]
We shouldn't be logging outside of the known loggers for a typical Android client.  The catchall covers things like MockWebServer.  So I think this is ok.

**Comment by Rshalika** [comment]
Hello,

How do I create jar file from master branch? I really need this fix and can't wait for the release.

Thanks
