### ISSUE TITLE
Support for version okhttp 3.14.x

### ISSUE THREAD

**Issue by magowdar** [square/okhttp#6124]
As per https://square.github.io/okhttp/security/#supported-versions : 3.14.x is supported only till Until 2020-06-30, even though latest 3.14.9 is released in 2020-05-17, Is there any reason behind this ? Or is there a typo ? 

Also I am able to see support for 3.12.x is till 2021-12-31, and there is a note saying : Java 7+. Platforms may not support TLSv1.2. : Does it mean , with 3.12.x TLS 1.2 will not work ?

**Comment by yschimke** [comment]
Everything on that page is correct.

3.12.x is a maintenance branch that supports down to Android API 9 if you need that.  However on those devices you might not have TLSv1.2 and as such you are also accepting higher risk with less secure connections.  On modern Android devices, 3.12.x will support event TLSv1.3

If you run an emulator with version 16 you will likely get TLSv1.0 connecting to facebook

```
06-10 08:06:29.349 2144-2156/? I/System.out: TLS_1_0
```

If you are happy to bundle and install conscrypt-android yourself, you should get TLSv1.2

```
      Security.insertProviderAt(Conscrypt.newProvider(), 1)
...
06-10 08:09:41.619 2205-2217/? I/System.out: TLS_1_2
```  

3.14.x bumped to Java 8, since we also support JVM developers who need more modern features.  Blog post here.

https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5

In 4.x when we moved to Kotlin as an implementation language, there wasn't much involved to upgrade (see proguard instructions in the second link below etc).  But we also kept 3.14.x as a final cut before the move, and decided to support it temporarily while people upgraded.

From July you can keep using 3.12.x if legacy clients are critical to you, or you can upgrade to 4.x which is actively developed.

https://cashapp.github.io/2019-06-26/okhttp-4-goes-kotlin
https://square.github.io/okhttp/upgrading_to_okhttp_4/

Also, as you can see from https://github.com/square/okhttp/pull/6121, we won't accept non-security fixes for 3.12.x.

**Comment by magowdar** [comment]
Hi Thanks for clarification. 

We are not using okhttp for Android. We are using to achieve http2 protocol in one of our java application where we use Java 11 with TLS 1.2 support. 

Can we use 3.12.x in this case ?

**Comment by yschimke** [comment]
@magowdar Yes, but there have been a lot of fixes and performance improvements in 4.x so if you file a bug report, it's likely we will just ask you to upgrade to 4.x.

Any reason you are avoiding upgrading to 4.x?

**Comment by magowdar** [comment]
@yschimke  Since 4.x has some API changes also , some time is needed for upgrading to 4.x. Based on some critical process timeline, we wanted to go for immediate easily available solution , so thought to upgrade to 3.X.x .. 
We have plan to upgrade to 4.x in coming month.
