### ISSUE TITLE
mutli thread to download a file and get error "Unexpected status line"

### ISSUE THREAD

**Issue by qyzhaojinxi** [square/okhttp#6161]
How can I solve this problem now? It's still the only way?

Most likely the preceding response was malformed. You should tell the web server’s administrator to fix this.

Work-around by disabling connection pooling on requests to this host. The easiest way is with this request header:
```
Connection: close
```

_Originally posted by @swankjesse in https://github.com/square/okhttp/issues/3662#issuecomment-338446870_

**Comment by yschimke** [comment]
There is a good suggestion by @15characterlimi that it could be related to unsafe use from multiple threads.  You shouldn't consume from a single Response across threads.

But otherwise, this alone isn't reproducible, please post a question to stackoverflow with sample code.

If you can make a clean reproduction, then reopen this issue.  But as is, we can't do much here.  Sorry.
