### ISSUE TITLE
Lower the visibility of the content of the okhttp.internal package to internal from public

### ISSUE THREAD

**Issue by LouisCAD** [square/okhttp#6226]
Because having it show up in autocomplete in so many places is annoying and I need to double check if it's from the stdlib, my code, or a lib almost every-time just because I use OkHttp.

If there's any reason to not have it `internal`, I'd like to know about it and see if we can work around these hypothetical reasons to resolve this issue.

**Comment by JakeWharton** [comment]
You can add it to your input excludes to work around.

**Comment by LouisCAD** [comment]
Fair point, though inconvenient to add to all projects for all affected users.

Are these public because used in multiple modules of OkHttp? If so, I'd suggest to make these artifacts depend on a new module called `internal` with the `implementation` scope, and move the content of the `internal` package here.

**Comment by JakeWharton** [comment]
Yes, but they have cyclic dependencies with public types so that won't work. We can use friend modules if the IDE support ever ships.

**Comment by yschimke** [comment]
I'm against this because I occasionally want to explore things that don't have public API for, with full knowledge that it's likely to break.  And there will likely be a lot more voices demanding that we open it up again.  For example https://github.com/square/okhttp/issues/6237 with open methods for mocking.

Anyway closing for now, we should maybe revisit this after 6 months or so, maybe it's a stronger convention as Kotlin adoption increases.
