### ISSUE TITLE
Support returning OkHttpClient subclasses from OkHttpClient.Builder#build()

### ISSUE THREAD

**Issue by chrisfillmore** [square/okhttp#6242]
Hello,

Here is a simplified view of my problem:

```
class MyOkHttpClient : OkHttpClient() {
  // override something here
}

val client = MyOkHttpClient()
val newClient = client.newBuilder().build()
```

Given the above code, I would like `newClient` to be an instance of `MyOkHttpClient`.

My use case is: I'm trying to inspect websocket network traffic on Android. This isn't supported by Android Profiler as far as I can tell, but it seems it should be possible with Stetho with a bit of work: http://zenandroid.io/monitoring-websockets-with-stetho/

However, I'm using OkHttp via Ktor. I can provide a preconfigued instance of OkHttpClient to Ktor, but the Ktor OkHttpEngine calls `newBuilder().build()` and thus ends up using OkHttpClient, not MyOkHttpClient:

https://github.com/ktorio/ktor/blob/21bb0a7a05f135a5ffb312ef83149fbc25899b86/ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpEngine.kt#L133-L144

It would seem the purpose of declaring OkHttpClient to be `open` is obviated somewhat by the fact that Builder#build() always returns OkHttpClient. Allowing users to override Builder#build() or pass a factory for creating instances of OkHttpClient would address this.

How do you feel about this?

Thanks

**Comment by JakeWharton** [comment]
How do we instantiate your subclass? How do you pass required arguments to the superclass? How do we maintain binary compatibility when we add a new required builder method whose value needs passed into the constructor?

**Comment by JakeWharton** [comment]
`OkHttpClient` is `open` to maintain binary compatibility with 3.x whose class was non-final because there were requests to `spy` on it with Mockito. This is generally not something we want to support, and if we broke binary compatibility we would likely make the type final again. Inheritance is not a mechanism we want to support.

How are you even calling the superclass constructor? It's marked as `internal`.

**Comment by chrisfillmore** [comment]
OkHttpClient has a public no-arg constructor. I'm using v4.8.1.

If OkHttpClient is `open` just for compatibility purposes, then I agree it's not worth making things further `open`. That sounds like a can of worms. But I was curious if it was expressly designed that way so people could override methods. Sounds like no!

The reason I am looking at Ktor is to avoid a callback-based API. I'll see if I can take my beef up with them. Thanks for responding!

**Comment by JakeWharton** [comment]
Yeah that constructor is a convenience for `new Builder().build()`, so it wouldn't be suitable for calling from a subclass since you would be ignoring all of the set properties of the user `Builder`.

I'm not sure what Ktor is doing, but we have `Call.Factory` and `WebSocket.Factory` interfaces which is what they should ideally be accepting. They can have a function which accepts an `OkHttpClient`, but it should just be a convenience for setting the `Call.Factory` and `WebSocket.Factory`. This is how Retrofit is designed, and it means you can insert yourself as a custom `Call.Factory` to decorate calls without needing to know anything about the `OkHttpClient`.

Does using the event listener API provide sufficient hooks for you to observe traffic?

**Comment by chrisfillmore** [comment]
Calling the Stetho method `NetworkEventReporter#webSocketFrameSent` depends on overriding OkHttp method `WebSocket#send()`. For example:

```
class StethoWebSocket(
  private val wrappedSocket: WebSocket,
  private val requestId: String
 ) : WebSocket by wrappedSocket {
  private val reporter = NetworkEventReporterImpl.get()

  override fun send(text: String): Boolean {
    reporter.webSocketFrameSent(SimpleTextInspectorWebSocketFrame(requestId, text))
    return wrappedSocket.send(text)
  }

  override fun send(bytes: ByteString): Boolean {
    reporter.webSocketFrameSent(SimpleBinaryInspectorWebSocketFrame(requestId, bytes.toByteArray()))
    return wrappedSocket.send(bytes)
  }
}
```
Other reporting methods (`webSocketFrameReceived`, etc) depend on OkHttp `WebSocketListener`.

I have filed an issue with Ktor:
https://youtrack.jetbrains.com/issue/KTOR-951

**Comment by chrisfillmore** [comment]
Just to follow up, in case anyone has a similar use case, my pull request with Ktor was merged and it is now possible to pass a `WebSocket.Factory` to its configuration:
https://github.com/ktorio/ktor/pull/2035
