### ISSUE TITLE
Expose APIs for developers to interact with the TCP connection

### ISSUE THREAD

**Issue by JamesChenX** [square/okhttp#6319]
**Motivation**
We need to set up a TCP(+TLS) connection to our server and okhttp should be a good solution because it has done a lot of job to adapt to different devices but unfortunately, it mixes the logic of TCP with the logic of application protocols (like HTTP/WS) and doesn't expose APIs to interact with the TCP connection for developers.

**Expectation**
So we need to confirm if there is any plan for exposing TCP-level APIs for developers? if not, we will support it by ourselves.
Thanks.

**Comment by swankjesse** [comment]
Can you configure the SocketFactory?

**Comment by swankjesse** [comment]
One example: https://github.com/square/okhttp/blob/master/samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/ClientAndServer.java

**Comment by JamesChenX** [comment]
@swankjesse Thanks for your quick reply. I have checked the example but that's not what we desire.
okhttp can only send HTTP requests or WebSocket frames currently, but we want to send data over the pure TCP(+TLS) connection without any application protocols.
Okhttp has adapted SocketFactory (with TLS support) to different devices and that's the main reason we want to use okhttp.

**Comment by swankjesse** [comment]
To clarify: you want to use OkHttp without HTTP?

**Comment by JamesChenX** [comment]
Yes.
We don't use HTTP and WebSocket and we want to use the TCP connection (Socket).
We still want to use okhttp because it's trivial to set up a TCP connection with TLS support that can run on all kinds of devices and we don't want to reinvent the wheel because okhttp has done the job.

**Comment by yschimke** [comment]
My 2c, I wouldn't like to support this as a maintainer :) 

This is a pretty crowded space already. It's unlikely we would get much adoption given how awesome Netty is, and there are lots of nuts and bolt toolkits for Kotlin also. It sounds like a support nexus if it does get adoption lots of interesting edge cases since we don't control it's usage via a higher level API.  HAve a look at the types of bugs and performance regressions Netty deals with daily, 10x the volume we do.

I suspect we'd be maintaining a public API specifically for you.

Throwing out various random suggestions

1) Take a cut of the current platform code, strip everything else out and maintain it yourself, just follow along for the occasional changes we make.
2) As above but make it a feature of something like ktor-io, potentially a niche project for cross platform, android, jvm, native.  Something that makes sense for that project would be awesome.
3) Use OkHttp 3.12 and use the internal API which have the features you need without the internal restrictions from Kotlin.

**Comment by JamesChenX** [comment]
@yschimke Thanks for your confirmation and suggestions. I understand your concern and we will take a cut of OkHttp code and adapt it to our project. Thanks.

**Comment by yschimke** [comment]
The kotlin MP cross platform socket library sounds super cool built on Okio (MP).  Unfortunately it's not OkHttp but it's a nice space in the world.

**Comment by yschimke** [comment]
Posting a link here on cross platform kotlin websockets https://kotlinlang.org/docs/mobile/connect-to-platform-specific-apis.html#example-send-and-receive-messages-from-a-websocket

The cross platform socket api would be an interesting space
