### ISSUE TITLE
Encrypted SNI or ClientHello

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6539]
tracking bug

Boring SSL - https://bugs.chromium.org/p/boringssl/issues/detail?id=275

Conscrypt - https://github.com/google/conscrypt/issues/730

Reference from Tunnel Bear to contributions to enable for OkHttp (seems blocked)
https://www.tunnelbear.com/blog/tunnelbear-implements-encrypted-sni/
https://boringssl-review.googlesource.com/c/boringssl/+/42644

Now ECH - https://blog.cloudflare.com/encrypted-client-hello/

**Comment by Luxusio** [comment]
When will the feature be added?

**Comment by yschimke** [comment]
No current plans and waiting upstream for support.  If you need it I suggest patching Conscrypt with the attached links above.

**Comment by eighthave** [comment]
I'm just starting to work on implementing ECH in Conscrypt, once boringssl supports ECH client-side.  I'll track progress in google/conscrypt#730

**Comment by yschimke** [comment]
@eighthave Great, let me know how it's going, I'm keen to add support for this with Conscrypt to OkHttp.

**Comment by eighthave** [comment]
Ok, good to know!  Have you looked into ECH much yet?  One key piece that I'm 
interested in is making sure that client libs like Conscrypt and OkHTTP have a 
good API for providing the ECH public key material.  This means something that 
works without DNS.  While DNS serves the majority of the cases well, ECH does 
not require DNS, and there are many important, minority use cases that are only 
possible if there is a way other than DNS to provide the required public key 
material.

We can start thinking about this and working out the API now, since the spec is 
getting close to RFP, and there are already implementations that provide 
something similar, like our (DeFO's) curl implementation of ECH that we are 
working on upstreaming.

**Comment by yschimke** [comment]
Does DNS over HTTPS help here? Overall I'm hoping that 80% of complexity is in BoringSSL, 15% in Conscrypt and 5% in flipping a switch in OkHttp's ConscryptProvider, or prior to explicit calls to socketFactory and sslSocketFactory.

**Comment by eighthave** [comment]
There are use cases where the site operator does not want to publicly advertise a specific setup, so they want to keep that info out of DNS.  Anyone can query DNS, so its public info.  For example, if a company wants to provide tunneling services via their website for employees traveling to places where VPNs are blocked.  Or ideas like MASQUE in IETF.

So yes, 80% of the compexity will be in boringssl, then most of the rest in Conscrypt.  OkHTTP should just expose the Conscrypt API for feeding ECH key material, etc.  This is likely dead simple, for example, like this in _curl_:

```
curl --echconfig \
  AEL+CgA+8QAgACCsEiogyYobxSGHLGd6uSDbuIbW05M41U37vsypEWdqZQAEAAEAAQAAAA1jb3Zlci5kZWZvLmllAAA= \
  https://draft-10-echonly.esni.defo.ie:9410/
```

**Comment by eighthave** [comment]
So I have ECH working in Conscrypt at the most basic level, now I'm looking for feedback for how to best implement the API for getting the ECH Config List bytes through Conscrypt into boringssl.  There are just two things needed:

* A method to pass in `byte[] echConfigList` that matches a given URL
* A method to enable/disable [ECH GREASE](https://www.ietf.org/archive/id/draft-ietf-tls-esni-13.html#name-do-not-stick-out) at least on the global level, but maybe also per connection.

I'm not familiar with how OkHTTP is implemented.  Does OkHTTP already have the ability to do arbitrary DNS query types?  Otherwise https://github.com/dnsjava/dnsjava already has [ECH](https://javadoc.io/doc/dnsjava/dnsjava/latest/org/xbill/DNS/SVCBBase.ParameterEch.html) support implemented. Either of those options are needed to start working with [`HTTPSSVC` / `SVCB`](https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-07.html#ech-param) DNS queries to get the ECH Config List.  The TLS client gets the ECH relevant public keys from the ECH Config List.  Right now, I'm thinking that the ECH Config List and ECH GREASE set via the `javax.net.ssl.SSLParameters`.

**Comment by eighthave** [comment]
Is using [DnsResolver.rawQuery()](https://developer.android.com/reference/android/net/DnsResolver#rawQuery(android.net.Network,%20java.lang.String,%20int,%20int,%20int,%20java.util.concurrent.Executor,%20android.os.CancellationSignal,%20android.net.DnsResolver.Callback%3C?%20super%20byte[]%3E)) an option here?  In theory, it would allow the required DNS to happen using the device's system resolvers.

**Comment by yschimke** [comment]
From the plan you've laid out, once it's working in Conscrypt, we should have a viable blueprint for using it in Android without any changes to OkHttp itself. I think any API or implementation changes could follow from active use and feedback of this.

**Comment by yschimke** [comment]
@eighthave Nice - saw the announcement https://groups.google.com/d/msgid/conscrypt/cb054dad-5f76-5f10-c4d3-868179d221f0%40guardianproject.info

Does this mean it likely won't go into Conscrypt main itself?

I'd personally love to at least get a sample showing this can work with OkHttp, and happy to help with it.

**Comment by eighthave** [comment]
My goal has always been to get Google to merge it, but that's up to them.  In 
theory, the binary that I posted on Maven Central should be enough for you to 
get ECH working with OkHTTP.  That's the first release, so I expect bugs.  You 
could try first letting it handle the DNS, but that part of the code is likely 
the most brittle, since handling DNS in Conscrypt is totally new.  Since OkHTTP 
can already handle DNS, I think it should be possible to do DNS with OkHTTP and 
get ECH working pretty solidly.

**Comment by yschimke** [comment]
I think that's a good target.  DnsOverHttps won't fetch the additional fields, so seems like we'd need a custom Android Dns or DnsJava?.

I don't think Conscrypt exposes any way to get the session keys for Wireshark, so I assume in this case I'll need to just get it connected and assume it works.

**Comment by eighthave** [comment]
Yuri Schimke:
> I think that's a good target.  DnsOverHttps won't fetch the additional fields, so seems like we'd need a custom Android Dns or DnsJava?.

You can use the DNS stuff I wrote to get things going, that should be easy to 
follow in https://github.com/defo-project/EchInteropTest

Since you have a DoH implementation, I think you'll want to implement HTTPS/SVCB 
RR types.  It seems a perfect fit to OkHTTP's mission since it gives the entire 
HTTPS config in a single DNS query, including ECH Config, CNAMEs, port to use 
(e.g. 443 or 80), etc.

> I don't think Conscrypt exposes any way to get the session keys for Wireshark, so I assume in this case I'll need to just get it connected and assume it works.

There is `Conscrypt.echAccepted()` to check, if that's what you mean.

**Comment by yschimke** [comment]
I've put a rough working draft here https://github.com/yschimke/okhttp/tree/ech

Run https://github.com/yschimke/okhttp/blob/ech/android-test/src/androidTest/java/okhttp/android/test/EchTest.kt

But it feels very close.  The pieces are wired up crudely.

**It's not working**

```
error:1000013f:SSL routines:OPENSSL_internal:ECH_REJECTED (/builds/eighthave/conscrypt/boringssl/ssl/handshake_client.cc:1800 0x71ba17e3a6ba:0x00000000)
		... 120 more
	Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x71bb1ab14118: Failure in SSL library, usually a protocol error
error:1000013f:SSL routines:OPENSSL_internal:ECH_REJECTED (/builds/eighthave/conscrypt/boringssl/ssl/handshake_client.cc:1800 0x71ba17e3a6ba:0x00000000)
		at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
```

I'm basically not sure how to take the HTTPS structure in the result records and pass it into your Conscrypt method.

**Where it should live**

Probably not in OkHttp in the near future, especially if it isn't in Conscrypt.  It seems like it should be possible as a clean combination of Dns (Android or DnsJava), Conscrypt (with your patch), 

Looking at https://github.com/dnsjava/dnsjava/blob/700856f1c984324f4ad1bcdf0c02084c0203a109/src/main/java/org/xbill/DNS/DohResolver.java it isn't for production usage, and suggests combining with OkHttp.

**To decide**

Whether to start with the ipv4 and ipv6 hints in HTTPS record.

Which DNS to build on
- A clone and extension of DnsOverHttp in OkHttp?
- DnsJava
- Android DnsResolver

**Comment by yschimke** [comment]
Working, apparently the crypto.cloudflare.com server only supports certain urls :(

```
02-06 01:05:19.047 10149 13080 13102 I System.out: ECH was active true
...
02-06 01:05:19.113 10149 13080 13102 I System.out: fl=377f339
02-06 01:05:19.113 10149 13080 13102 I System.out: h=crypto.cloudflare.com
02-06 01:05:19.114 10149 13080 13102 I System.out: ip=81.100.210.134
02-06 01:05:19.114 10149 13080 13102 I System.out: ts=1644166044.796
02-06 01:05:19.114 10149 13080 13102 I System.out: visit_scheme=https
02-06 01:05:19.114 10149 13080 13102 I System.out: uag=okhttp/5.0.0-SNAPSHOT
02-06 01:05:19.114 10149 13080 13102 I System.out: colo=LHR
02-06 01:05:19.114 10149 13080 13102 I System.out: http=http/2
02-06 01:05:19.114 10149 13080 13102 I System.out: loc=GB
02-06 01:05:19.114 10149 13080 13102 I System.out: tls=TLSv1.3
02-06 01:05:19.114 10149 13080 13102 I System.out: sni=encrypted
02-06 01:05:19.114 10149 13080 13102 I System.out: warp=off
02-06 01:05:19.114 10149 13080 13102 I System.out: gateway=off
```

**Comment by yschimke** [comment]
My suggested setup.

1a) A DnsJava implementation of okhttp Dns that works on Android or JVM, maybe even configuring itself intelligently, baesd on network settings, or just defaults to 1.1.1.1
1b) An Android implementation of Dns - probably just checking that it's really using Dns over Tls or Https?
2) Cleanup the setup With Dns, and a DelegatingSSLSocketFactory that configures the socket.
3) a project somewhere to host this with a suitable license 

I don't think OkHttp DnsOverHttp should be expanded, it's a very specific implementation stripped down from Netty.  If you want this setup, using DnsJava doesn't sound unreasonable.  But your call.

Thanks for driving this, and hope I can help you get this over the line.

**Comment by yschimke** [comment]
I think we are at the same place, the right abstractions exist in OkHttp that it would be possible to implement it given a supported DNS and SSL stack.  So encouragement is probably more useful in the Conscrypt issue.

**Comment by eighthave** [comment]
FYI, it is looking like we have secured a second round of funding, so I 
hopefully I'll be active again soon.

**Comment by yschimke** [comment]
This is possible for experimentation now.  However I don't see support in Conscrypt landing in a way we can use any time soon.

I don't think we plan to implement this as a core OkHttp feature.

**Comment by yschimke** [comment]
Testing what a built in by default implementation for Android would look like https://github.com/square/okhttp/pull/9383

**Comment by yschimke** [comment]
@eighthave I've updated that branch for SDK 37 APIs.
