### ISSUE TITLE
Disable all logging

### ISSUE THREAD

**Issue by dsuresh-ap** [square/okhttp#6595]
We noticed that even without a `HttpLoggingInterceptor`, logs could be made by the library through `Platform.get().log(..)`. We would like to disable all logging in case any sensitive information gets outputted through exceptions or stacktraces.

Sample code of how we achieved this:
```
private fun disableNetworkingLogging() {
    if (!BuildConfig.DEBUG) {
        Platform.get() // Initialize Platform
        listOfNotNull(
            OkHttpClient::class.java.`package`?.name,
            OkHttpClient::class.java.name,
            Http2::class.java.name,
        ).forEach {
            Logger.getLogger(it).removeHandler(AndroidLogHandler)
        }
    }
}
```

A suggestion would be to add a `disable` function to `AndroidLog`.

Version: 4.0.9

**Comment by yschimke** [comment]
It should be short circuiting the logging unless you have configured it on.  Are you enabling logging generally, but then specifically want to disable OkHttp? Otherwise it sounds like a bug. OkHttp should be outputting based on the logging levels you have set for it.

**Comment by dsuresh-ap** [comment]
We have no logged enabled in the app and no logic to set OkHttp's logging level. We do set an HttpLoggingInterceptor with level `NONE` but we confirmed no logs are outputted through it.

We simplify tested this by calling `Platform.get().log(..)` in a non debuggable build and it outputs.

**Comment by yschimke** [comment]
I'll take another look. Could you send a sample of logs that make it through on a prod build.

**Comment by JakeWharton** [comment]
`Platform.log` is an abstraction over platform-specific logging sinks so calling it directly should result in a log. You are testing the underlying mechanism of writing to a log location, such as calling `System.out.println` directly.

**Comment by dsuresh-ap** [comment]
I forced `Platform.log` just to see if it will actually log but maybe I am misunderstanding.

For example in `RealCall.run()` there is a line: `Platform.get().log("Callback failure for ${toLoggableString()}", Platform.INFO, e)`.

I just want to confirm that without any change to OkHttp's log level settings will calls to `.log()` like the one above get logged?

**Comment by yschimke** [comment]
Default will be info https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)

In this case we don't have much choice because we are calling the callback to process the response, and that itself is failing with a IOException.  Unless we choose to silent swallow failures we don't have many options here.  You should fix your Callback to handle failures as opposed to rethrowing back into OkHttp. Then it won't cause anything to get logged.

It's also worth noting what is logged here

```

  /**
   * Returns a string that describes this call. Doesn't include a full URL as that might contain
   * sensitive information.
   */
  private fun toLoggableString(): String {
    return ((if (isCanceled()) "canceled " else "") +
        (if (forWebSocket) "web socket" else "call") +
        " to " + redactedUrl())
  }
```

We are already being sensitive to PII, if this is too much the two options you have are a) fix the bug in your code or missing catch clause causing failures in the callback, b) possibly adjust logging using the Android mechanisms.

**Comment by dsuresh-ap** [comment]
Understood.

I noticed that specific example strips any sensitive information. We just didn't want any other logs showing either, example for the Slack app that I see now and then: `W/okhttp.OkHttpClient: A connection to https://slackb.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);`

We already implemented `b` as shown in the first post. We just wanted to know if there was some method supported by the library (or in the future) to disable logging but if not feel free to close this issue. Thanks!

**Comment by yschimke** [comment]
The example above is a bug that should be fixed in the app, so I think the log at W is valid.

Given you already have a valid workaround, unless there are some more worrying examples I think you've already identified what we consider the appropriate and straight forward workaround.

Closing out unless some obviously bad examples are identified.
