### ISSUE TITLE
Add two options to the LoggingInterceptor

### ISSUE THREAD

**Issue by thokari** [square/okhttp#6665]
I created a REST API client based on this, and want to fine tune logging.
For this purpose I would like two have two options added to the logging interceptor:

1. Add the logging level `BODY_ONLY` to log the request body without logging the headers.
2. Add the option to pretty print the body. 

An alternative to adding another level would be to change the signature of the `log` method, to receive more (optional) parameters, i.e. `log(String message, String headers = null, String body = null)`, but I am not sure if this is possible without breaking existing implementations.

I just realised that the current implementation is actually passing the content line by line, so I could solve the 2. problem by simply waiting for a line that contains JSON, and pretty print that.

**Comment by JakeWharton** [comment]
In general, we do not want to add infinite control to the interceptor. If you want extreme customization you're better off duplicating it and implementing the desired behavior in your version.

For example, point 2 is impossible since it implies that 1. the format is text-based and 2. the format is known to OkHttp and can be pretty printed.
