### ISSUE TITLE
Add alternative to ALPN for case if server does not support ALPN

### ISSUE THREAD

**Issue by Machuzhenko** [square/okhttp#7036]
I faced with the issue that in TLS connection OkHttpClient can't connect to server via http2 if server does not support ALPN. 
The server that I tried to connect to, does not support ALPN, has disabled http1.1 and enabled http2. 
Investigating Client Hello and Server Hello messages, as I understood, OkHttpClient send ALPN extention with proposed http versions (1.1 and 2 by default) -> server does not recognize it because it does not support ALPN -> negotiation about http version does not occur -> OkHttpClient thinks that server does not support http2 -> OkHttpClient tries to connect via http1.1 -> connection is not eatablished.

In non secured connection we don't have such issue because we can use Protocol.H2_PRIOR_KNOWLEDGE. But in TLS connection it's impossible. 

So, I think, maybe we need some additional mechanism to negotiate about http version? Maybe, I miss something and OkHttpClient has it or there is some workaround?

**Comment by yschimke** [comment]
I think it's mandatory https://datatracker.ietf.org/doc/html/rfc7301#section-4

You should get this bug fixed in the server.  Possible you can override the SSLSocket to lie about this in the connection, but you'll have to dig in and see if it's technically possible, it could fail for other reasons.

We won't add this as an option as the server must support ALPN.

**Comment by yschimke** [comment]
Continued here https://stackoverflow.com/questions/70849839/how-okhttpclient-can-establish-tls-connection-via-http2-with-server-that-does-no
