### ISSUE TITLE
Add an OAuth2 Example in Java and Kotlin

### ISSUE THREAD

**Issue by Deceptio** [square/okhttp#7087]
I can't find a good example anywhere on the internet showing how to do an OAuth2 with okhttp and token renewal. 
The existing examples here in the repo are only simple examples and unfortunately without OAuth2.

Since okhttp is becoming more and more popular, that would certainly be a good thing

**Comment by yschimke** [comment]
I tried this and didn't like it https://github.com/square/okhttp/pull/7092/files

Hopefully this sample is useful for you.

I'm going to close this, I don't think a single sample can really explain all the variables in play such that it's helpful in a significant number of cases.

a) The callback URL requires running a server specific to your environment, or maybe alternatives when you are running in a mobile app.
b) Storing the access and refresh token is different on each platform.
c) The specific call details are annoyingly different for each API you want to use.

I think this example belongs ona library that handles oauth authentication, rather than down in OkHttp.  This problem is only trivial when you lock things down to a single API, platform and mobile/server app with it's own technical choices.

**Comment by Deceptio** [comment]
Thank you for your response, it is really kind of you that you wrote that example and share it. And yes it is very usefull for me and I understand your arguments and your are right.
In the meantime I did more research, and I understand that the OAuth2 is not a okhttp "problem", as you already mentioned.

But I know now what my problem is with regard to okhttp. -> When I have to use an interceptor and when an authenticator? Or both at the same time? 

In this example is only used an [authenticator](https://square.github.io/okhttp/recipes/#handling-authentication-kt-java).
I thought the interceptor is here to add a authentication TAG `.header("Authorization", credentials).build();` to the header, but WHEN  a 401 comes back, the authenticator is called to get a new token with a new request  and to write the new token into the original request header.

process example:
request-> interceptor -> 401 -> authenticator -> send request again

But in the example you wrote, you use an interceptor and you check inside the interceptor the 401 and then you get directly a new token? What do you think is the better recommendation? Or am I misunderstanding the concept?

Maybe i this a idea for a new recipe in the future, to show the the interaction between the interceptor and authenticator.

Thank you for your response and your time

**Comment by yschimke** [comment]
Authenticator is called after a 401. If you know the request needs auth headers before making the request the n interceptor saves a network call.

Plus refresh can be handled in same function.

Authenticator is called 0..n times, which we don't need.
