### ISSUE TITLE
Use Library without PublicSuffixes.gz file:

### ISSUE THREAD

**Issue by prady32** [square/okhttp#7095]
Hi,
We are trying to integrate okhttp library in chromium but chromium does not allow or pick publicSuffixes.gz file from okhttp resources hence the application always crashes. 
We have tried many ways but we cannot even manually add publicSuffixes.gz file into chromium.
 Is there any way so that we can make okhttp library ignore if publicSuffixes.gz file is not present and do not throw a crash.

Thanks,
Pradeep

**Comment by swankjesse** [comment]
Thanks for your question. This issue tracker is only for bug reports with test cases and feature requests. Please ask usage questions on Stack Overflow.
https://stackoverflow.com/questions/tagged/okhttp

**Comment by yschimke** [comment]
Do you have a stack trace? This really isn't actionable as is.

**Comment by prady32** [comment]
Hi @yschimke 

This is the stacktrace

java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.a(chromium-ChromePublic.apk-stable-179:49)
        at Lj0.d(chromium-ChromePublic.apk-stable-179:46)
        at Gj0.a(chromium-ChromePublic.apk-stable-179:41)
        at Nj0.b(chromium-ChromePublic.apk-stable-179:14)
        at Pj0.a(chromium-ChromePublic.apk-stable-179:34)
        at Nj0.b(chromium-ChromePublic.apk-stable-179:14)
        at vj0.j(chromium-ChromePublic.apk-stable-179:25)
        at sj0.run(chromium-ChromePublic.apk-stable-179:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

In the final apk publicsuffixes.gz file is not included. So its failing.

**Comment by yschimke** [comment]
Are you using PublicSuffixDatabase directly? It's an internal class that we don't expect to be used by clients.

I didn't think we failed like this normally as we often have this resource stripped by proguard or in native image.

I think we shouldn't fail when missing and used internally, and should fix this if so. But we can't guarantee this if you are using internal APIs directly.

**Comment by prady32** [comment]
Are you using PublicSuffixDatabase directly?
No we are not using it directly.

We do store some cookies in our app. So it might be calling that internally from library

**Comment by yschimke** [comment]
Took a look into this, I didn't realise that it happens if the resource is missing, but presumably because we only use it for Cookies and DnsOverHttps. I don't think we will change this as it does indicate a broken build, missing essential resources.

So you have a few options

1) Get the build to include the file.
2) Avoid calling it, so probably avoid OkHttp Cookie handling, do it manually.
3) Close your eyes and call internal methods that ferquently change, and maintain this yourself.

```
  val db = PublicSuffixDatabase.get()
  db.setListBytes(byteArrayOf(), byteArrayOf())
  println(db.getEffectiveTldPlusOne("www.google.com"))
```

I would advise against 3, and may break in some other ways, and likely to break in the future.  It's possible these classes become kotlin internal in future, rather than just public in an internal package. But presenting as an option in case you are desperate.
