### ISSUE TITLE
Allow Settings frame values to be adjusted

### ISSUE THREAD

**Issue by unlucku** [square/okhttp#7195]
I think this would be a nice feature for people who want to adjust the values sent in the Settings frame.
Looking at the code I believe all but ENABLE_PUSH and MAX_HEADER_LIST_SIZE are already supported and implemented, we would just have to change some static references.

For ENABLE_PUSH it does not really matter as very little servers support this anyway. I believe chrome might drop/disable it as a result soon (see https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ) as people have started to move towards early hints. Alternatively, if okhttp adds support for early hints, supporting server push should be relatively easy as well. I do hope this value can still be set, as it would help people trying to avoid SETTINGS fingerprinting. (This is becoming more and more common these days) 

And lastly I do not think MAX_HEADER_LIST_SIZE implementation would be difficult, however since it is an advisory setting I believe the current system works just as well. 

I would be happy to PR this myself, when I first started using okhttp I needed to customize the settings fingerprint too. I ended up implementing this on 4.x codebase (via attaching an int[] to the client) and updating it to work with the current repo should be relatively simple. I have seen too many people go with the option of using a http middleware written in go to be able to customize the settings frame. This is usually because they do not really have a solid understanding of Http or lack the time to adjust the code.

Pros:
 - Avoid SETTINGS fingerprinting
 - No more "Change window size to x because.."

Cons
- Bad/slow values being set by uninformed devs (Who will blame okhttp for the issues that result), similar to people copy pasting JVM GC flags without knowing their purpose, and then complaining about issues with GC caused by unneeded customization. This shouldnt be as prevelant with this though, I think it is worth giving it a shot!

**Comment by yschimke** [comment]
I don't think this really fits in well with the OkHttp design philosophy. Trying to do the right thing by default on all platforms without requiring a lot of configuration.

As you highlight it would introduce a new things to break and cause additional support from developers who use this.  And the code would have to handle those flags when they affect the behaviour of OkHttp.

If there are specific features we want, then I think those are more interesting, but still possibly don't meet the bar.  Such as allowing increasing window size because it is required for some particular networking setup.  Or an explicit flag for SETTINGS fingerprinting because it's important for security, but it would be good to see what other common clients are doing there, and make it a feature rather than just allowing a client to set it.

**Comment by swankjesse** [comment]
Agreed with @yschimke. We want to build application-layer APIs on top of protocol-layer data. In general we don’t want to expose protocol-layer data.
