### ISSUE TITLE
Failed to authenticate with proxy following upgrade to OkHttp3 APIs

### ISSUE THREAD

**Issue by jmcrawford45** [square/okhttp#7283]
I have okhttp as a transitive dependency of kubernetes-client-java, and I recently upgraded it (which upgraded from 2.7.5 to 4.9.2).

Before, I had a working client as follows (this is in scala, but hopefully similar enough to java for you to follow along)
```
// define the authenticator
new Authenticator {
      override def authenticate(
        proxy: Proxy,
        response: Response
      ): Request = {
        val credential = Credentials.basic(proxySecrets("username"), proxySecrets("password"))
        response.request.newBuilder.header("Proxy-Authorization", credential).build
      }

      override def authenticateProxy(
        proxy: Proxy,
        response: Response
      ): Request = {
        val credential = Credentials.basic(proxySecrets("username"), proxySecrets("password"))
        response.request.newBuilder.header("Proxy-Authorization", credential).build
      }
    }
...
// configure the authenticator
apiClient.getHttpClient.setProxy(proxy)
apiClient.getHttpClient.setAuthenticator(authenticator)
...
```
Now, the client fails to authenticate with "IOException: Failed to authenticate with proxy" after changing to the following
```
// define the authenticator
(_: Route, response: Response) => {
      val credential = Credentials.basic(proxySecrets("username"), proxySecrets("password"))
      response.request.newBuilder.header("Proxy-Authorization", credential).build
    }
...
// configure the authenticator
apiClient.setHttpClient(apiClient.getHttpClient.newBuilder().proxy(proxy).build())
apiClient.setHttpClient(apiClient.getHttpClient.newBuilder().proxyAuthenticator(authenticator).build())
...
```
Is this expected to work for OkHttp3 style APIs? Or have I missed some migration documentation that gives the correct way to configure a HTTPS proxy client with basic auth?

**Comment by yschimke** [comment]
Each newBuilder().build() call is creating a new instance that you are discarding. So you have one with nothing set being used. 

And one with proxy set never used.
And one with authenticator set never used.

You should create a single instance and set it once. Likely requiring changing how you build your own httpclient.

**Comment by yschimke** [comment]
Ahh, I missed both lines are setting it back. Sorry.

Curious why you don't do that in one operation? Why set a client that is only partially configured?

**Comment by yschimke** [comment]
I'm at a loss to see how to help here. The change I can think of related to proxies is not falling back to direct if you have a proxy set.

https://square.github.io/okhttp/changelogs/changelog_3x/#version-350

_OkHttp no longer attempts a direct connection if the system’s HTTP proxy fails. This behavior was surprising because OkHttp was disregarding the user’s specified configuration. If you need to customize proxy fallback behavior, implement your own java.net.ProxySelector._

And https://square.github.io/okhttp/changelogs/changelog_3x/#version-300-rc1

_OkHttp no longer uses the global java.net.Authenticator by default. We’ve changed our Authenticator interface to authenticate web and proxy authentication failures through a single method. An adapter for the old authenticator is available in the okhttp-urlconnection module._

-----

But I'd suggest running these requests in a standalone program that just makes the requests through the proxy and confirm it works that way first.  I don't know how to help with this report since it seems you are setting fields correctly, just unusually but it should still work.

If you can't get that working, at least we have something to dig into.

If it does work in a standalone program, then you can add an event listener and see the events and then compare against requests in your existing app.

https://square.github.io/okhttp/features/events/

https://github.com/square/okhttp/blob/8a08fb2652043a180eeb4b0b03d7bb5cbb00bea3/okhttp/src/jvmMain/kotlin/okhttp3/EventListener.kt

**Comment by jmcrawford45** [comment]
I was able to tunnel locally to the proxy and verify connectivity both with curl and with a very similar client configuration. I'll install the event listeners so I can hopefully get an exact trace of where these clients differ.

**Comment by jmcrawford45** [comment]
locally, I see 
```
0.0 callStart
0.001251958 connectionAcquired
0.001640708 connectionReleased
0.001714791 proxySelectStart
0.001771958 proxySelectEnd
0.001817833 dnsStart
0.001894208 dnsEnd
0.002687041 connectStart
2.610629458 connectStart
3.021885416 secureConnectEnd
3.024002541 connectEnd
3.0274635 connectionAcquired
3.028942208 requestHeadersStart
3.029697333 requestHeadersEnd
3.217700958 responseHeadersStart
3.218597041 responseHeadersEnd
```
but in my application, I see 
```
2022-05-25 21:35:30,594 ERR                  0.0 callStart
2022-05-25 21:35:30,594 ERR                  1.33251E-4 proxySelectStart
2022-05-25 21:35:30,594 ERR                  4.79244E-4 proxySelectEnd
2022-05-25 21:35:30,594 ERR                  6.55255E-4 dnsStart
2022-05-25 21:35:30,594 ERR                  7.23246E-4 dnsEnd
2022-05-25 21:35:30,595 ERR                  0.001030068 connectStart
2022-05-25 21:35:30,596 ERR                  0.00245719 connectFailed
2022-05-25 21:35:30,596 ERR                  0.002619021 callFailed
```

**Comment by jmcrawford45** [comment]
I was able to identify and fix the issue. Basically, around the same time as the upgrade, we also removed proxy requirement from the affected clients. So while I was seeing a proxy configured for them, it was not the old proxy that we previously used, but instead it inferred the proxy from `https.proxy*` system properties. Also, the authenticator had stopped being inferred from global default per https://square.github.io/okhttp/changelogs/changelog_3x/#version-300-rc1. I was able to ensure these are unset. If we need a system property proxy in the future, we'll stub a ProxySelector that always returns `List.empty` for these clients. Thanks for your help with this @yschimke
