### ISSUE TITLE
Interceptors simplification

### ISSUE THREAD

**Issue by cyberhck** [square/okhttp#7436]
Not kinda a problem I'm trying to solve but rather streamlining the API contracts.

I'm looking at interceptors and see there are two types of interceptors: `ApplicationInterceptor` and `NetworkInterceptor`, could we not reconcile them to just `Interceptor`? As far as okhttp is concerned, it's just a chain of interceptors. And weather or not a chain calls next middleware in the chain shouldn't even be a concern, should it?

Is that the intended design? Or something we could change? Is there a reason for it?

From okhttp point of view, I wouldn't care what middleware does, from a middleware author's point of view, I decide what my middleware does, I could short circuit or chose not to.

And most features in okhttp ecosystem could just be another middleware. Instead of okhttpmock server, we could have a MockMiddleware, instead of Authenticator we could have auth middleware etc.

What do you think? :slightly_smiling_face:

**Comment by yschimke** [comment]
Firstly it's a non starter to blow up the existing API on OkHttpClient.Builder because of strong API guarantees we have. Streamlining is not a goal. 

It sounds like you are asking to make a single interceptor list. That defaults to the BridgeInterceptor, but allows you to remove it, insert (application) interceptors before it, and (network) interceptors after it.

But this is pretty much what happens internally 

```
  internal fun getResponseWithInterceptorChain(): Response {
    // Build a full stack of interceptors.
    val interceptors = mutableListOf<Interceptor>()
    interceptors += client.interceptors
    interceptors += RetryAndFollowUpInterceptor(client)
    interceptors += BridgeInterceptor(client.cookieJar)
    interceptors += CacheInterceptor(client.cache)
    interceptors += ConnectInterceptor
    if (!forWebSocket) {
      interceptors += client.networkInterceptors
    }
    interceptors += CallServerInterceptor(forWebSocket)

    val chain = RealInterceptorChain(
        call = this,
        interceptors = interceptors,
        index = 0,
        exchange = null,
        request = originalRequest,
        connectTimeoutMillis = client.connectTimeoutMillis,
        readTimeoutMillis = client.readTimeoutMillis,
        writeTimeoutMillis = client.writeTimeoutMillis
    )
```

Without changing that current API, is there something you are missing?

As an example https://github.com/google/cronet-transport-for-okhttp is set as the final application interceptor and stops the BridgeInterceptor, network interceptors, and CallServerInterceptor from being invoked.

**Comment by cyberhck** [comment]
The above code helps to understand this a little better. Is there a way to make this chain myself instead of being done internally? But I'm already happy with this, I could choose an application interceptor that doesn't call next but rather calls my own chain.

However, if I could do something like this:
```
OkHttp.WithInterceptorChain(buildInterceptorChain(applicationInterceptors, networkInterceptors))
```
That way, normal people use this and if someone wanted to use something else, they could. But thanks for the response, I'm already happy with your response :slightly_smiling_face:
