### ISSUE TITLE
Could you please let  other module class to extend OkHttpClient?

### ISSUE THREAD

**Issue by trydofor** [square/okhttp#7721]
Because of the following requirements, we hope to use a subclass (e.g. `MyOkHttpClient`) to extend `OkHttpClient`,

* reuse the `OkHttpClient` spring singleton  bean
* override `newCall` to customize the request (e.g. `myRequest`)
* cannot modify existing methods that take `OkHttpClient` as a parameter, but need to pass both `MyOkHttpClient` and `OkHttpClient` instance to them
* `myRequest` cannot be distinguished by url.
* `myRequest` only affects the `MyOkHttpClient` instance,  other `OkHttpClient` instances are unaffected

Here are my attempts, but none of them satisfy the requirements

* Use Interceptor, but `myRequest` can't distinguish the target based on request, and will also affect all the `OkHttpClient` instances
* Use Wrapper, but the original business method only supports `OkHttpClient`parameters

So, currently, the best way is to extend `OkHttpClient` and override `newCall`. and I do this in Java, got the warning like bellow, because of the `internal` keyword

> Usage of Kotlin internal declaration from different module 

https://github.com/square/okhttp/blob/ee1ba4656d80ed62485387217271c7fa31dc888e/okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt#L132-L134

I'm not sure what the effect of removing `internal` would be, and I don't know if there's a better solution.

Thanks in advance!

**Comment by trydofor** [comment]
https://github.com/square/okhttp/issues/7193

**Comment by yschimke** [comment]
No, this is by design. It is not open for extension. We frequently change the internals, which is only possible because the public API is deliberate and minimal.

There is already an API exactly for this,  Call.Factory. libraries like Retrofit and Coil take Call.Factory instead of OkHttpClient exactly for this reason. You should file a bug with libraries that require OkHttp only to change this.

If you need an interceptor to make decisions based on the request and URL is not enough, then you should use tags to differentiate this.
