### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by andreaippo** [square/okhttp#7993]
Genuine question. Last release is months old and I didn't see any reply to the issue requesting a target date for the release of version 5.0.0.

I'd like to know if I have to look for alternatives, as I don't like having dead/unmaintained projects in my dependencies.

Thanks! :)

**Comment by yschimke** [comment]
The project is still alive.

4.x stable gets routine fixes https://github.com/square/okhttp/commits/okhttp_4x

5.x is alpha, because it's not imminently close to being API stable. But the Alphas are production quality.

But full disclosure
- There isn't a rush to get a 5.0 out, in fact we are likely to rework some of the KMP API code.
- We aren't planning major new investments into functionality like HTTP/3.

**Comment by andreaippo** [comment]
Thanks, Yuri.

That's reassuring 👍🏻

Il mar 22 ago 2023, 18:37 Yuri Schimke ***@***.***> ha
scritto:
