### ISSUE TITLE
okhttp3 compatibility issue with Microsoft Graph API

### ISSUE THREAD

**Issue by hubgit1970** [square/okhttp#8002]
We are experiencing the following issue when using the okhttp3 library with microsoft graph api:
 
import com.microsoft.graph.authentication.IAuthenticationProvider;
import java.time.Duration;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
**import okhttp3.Interceptor;
import okhttp3.OkHttpClient;
import okhttp3.OkHttpClient.Builder;**
 
public class HttpClients {
@Nonnull
public static Builder custom() {
return (new Builder())
.addInterceptor(new TelemetryHandler()).followRedirects(false)
.followSslRedirects(false).**connectTimeout**(Duration.ofSeconds(100L))
.readTimeout(Duration.ofSeconds(100L)).callTimeout(Duration.ofSeconds(100L));
}
 
java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.connectTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;
 
**Library versions:**
•	azure-core-1.42.0
•	azure-identity-1.10.0
•	jackson-datatype-jsr310-2.15.2
•	**microsoft-graph-5.68.0 >>> latest version**
•	microsoft-graph-core-2.0.19
•	**okhttp-4.11.0**
•	reactive-core-3.5.9
•	reactive-streams-1.04

**Comment by yschimke** [comment]
Can you provide a full stacktrace, it looks like something is pulling in an old version. It's really unlikely it's an issue for us, and not your build.

A stacktrace will provide clues to the version.

**Comment by hubgit1970** [comment]
java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.connectTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;
	at com.microsoft.graph.httpcore.HttpClients.custom(HttpClients.java:33)

The code snippet shows which libraries are being called.

**Comment by yschimke** [comment]
This isnt enough to go on. Unless you can make a reproduction for us, you'll have to into why you are pulling in an old version.

**Comment by mtotschnig** [comment]
I have run into the same problem in an Android project under the following condition:

- Microsoft Graph library is used in a dynamic feature module: minSdk must be set to 26, otherwise build fails because Microsoft Graph uses MethodHandle.invoke.
- The app module has minSdk 21 and coreLibraryDesugaringEnabled set to true. okhttp is included in app module.

Now okhttp library is desugared with Method connectTimeout(Duration) being rewritten. Microsoft Graph library is not desugared because of minSdk 26 and tries to call the non-desugared method which no longer exists leading to NoSuchMethodError.

**Comment by yschimke** [comment]
Nice find.  Might be worth raising an issue against AGP?
