### ISSUE TITLE
Expected a SETTINGS frame but was WINDOW_UPDATE

### ISSUE THREAD

**Issue by Blarc** [square/okhttp#8524]
**Describe the bug**
When making a request to OpenAI, an IOException is thrown. The error java.lang.RuntimeException: java.io.IOException: Expected a SETTINGS frame but was WINDOW_UPDATE is indicative of a problem that likely arises at the level of the HTTP/2 protocol, within model.generate call.

Supposedly works fine on Windows 10, but not on Ubuntu 22.04 [source](https://github.com/Blarc/ai-commits-intellij-plugin/issues/226#issue-2478169890).

**Log and Stack trace**
[tail_log.txt](https://github.com/user-attachments/files/16697472/tail_log.txt)

**To Reproduce**
I am not sure how to reproduce, since it doesn't always happen. The langchain4j is used as a dependency for IntelliJ plugin.

**Expected behavior**
The request to OpenAI to go through.

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: OpenAI (gpt-4o)
- Java version: 17

**Additional context**
https://github.com/Blarc/ai-commits-intellij-plugin/issues/226

**Comment by yschimke** [comment]
Does it happen for you, or for some other developer?  Are there any proxies in the way, like charles?

Anything that might be affecting the stream at the http/2 layer?

**Comment by Blarc** [comment]
Maybe @Trileon12 can provide that information, since he reported the issue.

**Comment by Trileon12** [comment]
Actually, on Ubuntu, I don't use a proxy (i mean ide proxy) because when I do, I receive a different error related to unsuccessful proxy authentication. 
But... at the router level, split tunneling is used, and requests to this server are currently routed through a WireGuard vpn connection. Could this be causing the issue?
Interestingly, on Windows, the same application in the same LAN works without triggering the "WINDOW_UPDATE" error. Additionally, it also works with proxy settings enabled in the ide without any issues.

**Comment by yschimke** [comment]
Wireguard should be at a lower layer, so shouldn't intercept any traffic

**Comment by yschimke** [comment]
Unless we can reproduce, it's going to be hard to fix.

You may want to provide an option to force http/1.1 in the OkHttp client. Or clearing the proxy in code as an option, see if that fixes the auth issue.
