### ISSUE TITLE
Inquiry About StreamResetException and SocketException Issues on Android

### ISSUE THREAD

**Issue by JeongJinyong** [square/okhttp#8571]
Hi,

We are experiencing the same issue described in the following thread: [Issue #3948](https://github.com/square/okhttp/issues/3948#issuecomment-384278758). We provide services across WEB, iOS, and Android platforms, but these two errors are notably occurring intermittently only on Android:

StreamResetException: stream was reset: CANCEL
java.net.SocketException: Socket closed
Initially, we suspected that the issue might be related to the Android lifecycle and how coroutines are being used in our ViewModel, leading to cancellations of API calls. However, we ruled out that possibility. After some research, we found that this problem seems to be related to OkHttp, and we came across the aforementioned issue.

As a workaround, we implemented the suggested solution of limiting the HTTP protocol to HTTP/1.1, and since then, the errors have stopped occurring. However, I have a few questions regarding this:

Why is this error happening?
Is limiting to HTTP/1.1 the only solution available, or are there any plans for a better fix?
What are your future plans regarding this issue?
Our service has approximately 100,000 monthly active users, and we noticed that these errors occurred for about 25,000 users in a month. This is not a trivial matter. Therefore, I am particularly interested in understanding why this error occurs and if there is any concrete solution beyond the HTTP/1.1 limitation.

Thank you for your attention.

**Comment by yschimke** [comment]
"stream was reset" indicates there is a clean cancellation, rather than an IO error. CANCEL rather than RST_STREAM indicates the client cancelled.

```
/** Thrown when an HTTP/2 stream is canceled without damage to the socket that carries it. */
class StreamResetException(
  @JvmField val errorCode: ErrorCode,
) : IOException("stream was reset: $errorCode")
```

Have a look at https://square.github.io/okhttp/features/events/, and consider adding an EventListener to get notified of the cancellation.  

As an example this is the stacktrace from CancelTest showing where it happened from.

```
java.lang.Exception: Cancelled Here
	at okhttp3.RecordingEventListener.canceled(RecordingEventListener.kt:274)
	at okhttp3.internal.connection.RealCall.cancel(RealCall.kt:148)
	at okhttp3.internal.http.CancelTest.cancelLater$lambda$13(CancelTest.kt:307)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

If you want further assistance, we'll need a reproduction to investigate.  

But this isn't an active issue for OkHttp to address, you should work out why your app is cancelling the request.
